// Code generated by ent, DO NOT EDIT.

package ccswitchimportconfig

import (
	"entgo.io/ent/dialect/sql"
	"github.com/router-for-me/CLIProxyAPI/v6/internal/storage/postgres/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldContainsFold(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldEQ(FieldTenantID, v))
}

// ClientType applies equality check predicate on the "client_type" field. It's identical to ClientTypeEQ.
func ClientType(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldEQ(FieldClientType, v))
}

// ProviderName applies equality check predicate on the "provider_name" field. It's identical to ProviderNameEQ.
func ProviderName(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldEQ(FieldProviderName, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldEQ(FieldNote, v))
}

// DefaultModel applies equality check predicate on the "default_model" field. It's identical to DefaultModelEQ.
func DefaultModel(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldEQ(FieldDefaultModel, v))
}

// ModelMappings applies equality check predicate on the "model_mappings" field. It's identical to ModelMappingsEQ.
func ModelMappings(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldEQ(FieldModelMappings, v))
}

// AllowedChannelGroups applies equality check predicate on the "allowed_channel_groups" field. It's identical to AllowedChannelGroupsEQ.
func AllowedChannelGroups(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldEQ(FieldAllowedChannelGroups, v))
}

// RoutePath applies equality check predicate on the "route_path" field. It's identical to RoutePathEQ.
func RoutePath(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldEQ(FieldRoutePath, v))
}

// EndpointPath applies equality check predicate on the "endpoint_path" field. It's identical to EndpointPathEQ.
func EndpointPath(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldEQ(FieldEndpointPath, v))
}

// UsageAutoInterval applies equality check predicate on the "usage_auto_interval" field. It's identical to UsageAutoIntervalEQ.
func UsageAutoInterval(v int) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldEQ(FieldUsageAutoInterval, v))
}

// APIKeyField applies equality check predicate on the "api_key_field" field. It's identical to APIKeyFieldEQ.
func APIKeyField(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldEQ(FieldAPIKeyField, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldContainsFold(FieldTenantID, v))
}

// ClientTypeEQ applies the EQ predicate on the "client_type" field.
func ClientTypeEQ(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldEQ(FieldClientType, v))
}

// ClientTypeNEQ applies the NEQ predicate on the "client_type" field.
func ClientTypeNEQ(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldNEQ(FieldClientType, v))
}

// ClientTypeIn applies the In predicate on the "client_type" field.
func ClientTypeIn(vs ...string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldIn(FieldClientType, vs...))
}

// ClientTypeNotIn applies the NotIn predicate on the "client_type" field.
func ClientTypeNotIn(vs ...string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldNotIn(FieldClientType, vs...))
}

// ClientTypeGT applies the GT predicate on the "client_type" field.
func ClientTypeGT(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldGT(FieldClientType, v))
}

// ClientTypeGTE applies the GTE predicate on the "client_type" field.
func ClientTypeGTE(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldGTE(FieldClientType, v))
}

// ClientTypeLT applies the LT predicate on the "client_type" field.
func ClientTypeLT(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldLT(FieldClientType, v))
}

// ClientTypeLTE applies the LTE predicate on the "client_type" field.
func ClientTypeLTE(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldLTE(FieldClientType, v))
}

// ClientTypeContains applies the Contains predicate on the "client_type" field.
func ClientTypeContains(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldContains(FieldClientType, v))
}

// ClientTypeHasPrefix applies the HasPrefix predicate on the "client_type" field.
func ClientTypeHasPrefix(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldHasPrefix(FieldClientType, v))
}

// ClientTypeHasSuffix applies the HasSuffix predicate on the "client_type" field.
func ClientTypeHasSuffix(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldHasSuffix(FieldClientType, v))
}

// ClientTypeEqualFold applies the EqualFold predicate on the "client_type" field.
func ClientTypeEqualFold(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldEqualFold(FieldClientType, v))
}

// ClientTypeContainsFold applies the ContainsFold predicate on the "client_type" field.
func ClientTypeContainsFold(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldContainsFold(FieldClientType, v))
}

// ProviderNameEQ applies the EQ predicate on the "provider_name" field.
func ProviderNameEQ(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldEQ(FieldProviderName, v))
}

// ProviderNameNEQ applies the NEQ predicate on the "provider_name" field.
func ProviderNameNEQ(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldNEQ(FieldProviderName, v))
}

// ProviderNameIn applies the In predicate on the "provider_name" field.
func ProviderNameIn(vs ...string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldIn(FieldProviderName, vs...))
}

// ProviderNameNotIn applies the NotIn predicate on the "provider_name" field.
func ProviderNameNotIn(vs ...string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldNotIn(FieldProviderName, vs...))
}

// ProviderNameGT applies the GT predicate on the "provider_name" field.
func ProviderNameGT(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldGT(FieldProviderName, v))
}

// ProviderNameGTE applies the GTE predicate on the "provider_name" field.
func ProviderNameGTE(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldGTE(FieldProviderName, v))
}

// ProviderNameLT applies the LT predicate on the "provider_name" field.
func ProviderNameLT(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldLT(FieldProviderName, v))
}

// ProviderNameLTE applies the LTE predicate on the "provider_name" field.
func ProviderNameLTE(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldLTE(FieldProviderName, v))
}

// ProviderNameContains applies the Contains predicate on the "provider_name" field.
func ProviderNameContains(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldContains(FieldProviderName, v))
}

// ProviderNameHasPrefix applies the HasPrefix predicate on the "provider_name" field.
func ProviderNameHasPrefix(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldHasPrefix(FieldProviderName, v))
}

// ProviderNameHasSuffix applies the HasSuffix predicate on the "provider_name" field.
func ProviderNameHasSuffix(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldHasSuffix(FieldProviderName, v))
}

// ProviderNameEqualFold applies the EqualFold predicate on the "provider_name" field.
func ProviderNameEqualFold(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldEqualFold(FieldProviderName, v))
}

// ProviderNameContainsFold applies the ContainsFold predicate on the "provider_name" field.
func ProviderNameContainsFold(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldContainsFold(FieldProviderName, v))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldHasSuffix(FieldNote, v))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldContainsFold(FieldNote, v))
}

// DefaultModelEQ applies the EQ predicate on the "default_model" field.
func DefaultModelEQ(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldEQ(FieldDefaultModel, v))
}

// DefaultModelNEQ applies the NEQ predicate on the "default_model" field.
func DefaultModelNEQ(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldNEQ(FieldDefaultModel, v))
}

// DefaultModelIn applies the In predicate on the "default_model" field.
func DefaultModelIn(vs ...string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldIn(FieldDefaultModel, vs...))
}

// DefaultModelNotIn applies the NotIn predicate on the "default_model" field.
func DefaultModelNotIn(vs ...string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldNotIn(FieldDefaultModel, vs...))
}

// DefaultModelGT applies the GT predicate on the "default_model" field.
func DefaultModelGT(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldGT(FieldDefaultModel, v))
}

// DefaultModelGTE applies the GTE predicate on the "default_model" field.
func DefaultModelGTE(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldGTE(FieldDefaultModel, v))
}

// DefaultModelLT applies the LT predicate on the "default_model" field.
func DefaultModelLT(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldLT(FieldDefaultModel, v))
}

// DefaultModelLTE applies the LTE predicate on the "default_model" field.
func DefaultModelLTE(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldLTE(FieldDefaultModel, v))
}

// DefaultModelContains applies the Contains predicate on the "default_model" field.
func DefaultModelContains(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldContains(FieldDefaultModel, v))
}

// DefaultModelHasPrefix applies the HasPrefix predicate on the "default_model" field.
func DefaultModelHasPrefix(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldHasPrefix(FieldDefaultModel, v))
}

// DefaultModelHasSuffix applies the HasSuffix predicate on the "default_model" field.
func DefaultModelHasSuffix(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldHasSuffix(FieldDefaultModel, v))
}

// DefaultModelEqualFold applies the EqualFold predicate on the "default_model" field.
func DefaultModelEqualFold(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldEqualFold(FieldDefaultModel, v))
}

// DefaultModelContainsFold applies the ContainsFold predicate on the "default_model" field.
func DefaultModelContainsFold(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldContainsFold(FieldDefaultModel, v))
}

// ModelMappingsEQ applies the EQ predicate on the "model_mappings" field.
func ModelMappingsEQ(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldEQ(FieldModelMappings, v))
}

// ModelMappingsNEQ applies the NEQ predicate on the "model_mappings" field.
func ModelMappingsNEQ(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldNEQ(FieldModelMappings, v))
}

// ModelMappingsIn applies the In predicate on the "model_mappings" field.
func ModelMappingsIn(vs ...string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldIn(FieldModelMappings, vs...))
}

// ModelMappingsNotIn applies the NotIn predicate on the "model_mappings" field.
func ModelMappingsNotIn(vs ...string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldNotIn(FieldModelMappings, vs...))
}

// ModelMappingsGT applies the GT predicate on the "model_mappings" field.
func ModelMappingsGT(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldGT(FieldModelMappings, v))
}

// ModelMappingsGTE applies the GTE predicate on the "model_mappings" field.
func ModelMappingsGTE(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldGTE(FieldModelMappings, v))
}

// ModelMappingsLT applies the LT predicate on the "model_mappings" field.
func ModelMappingsLT(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldLT(FieldModelMappings, v))
}

// ModelMappingsLTE applies the LTE predicate on the "model_mappings" field.
func ModelMappingsLTE(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldLTE(FieldModelMappings, v))
}

// ModelMappingsContains applies the Contains predicate on the "model_mappings" field.
func ModelMappingsContains(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldContains(FieldModelMappings, v))
}

// ModelMappingsHasPrefix applies the HasPrefix predicate on the "model_mappings" field.
func ModelMappingsHasPrefix(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldHasPrefix(FieldModelMappings, v))
}

// ModelMappingsHasSuffix applies the HasSuffix predicate on the "model_mappings" field.
func ModelMappingsHasSuffix(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldHasSuffix(FieldModelMappings, v))
}

// ModelMappingsEqualFold applies the EqualFold predicate on the "model_mappings" field.
func ModelMappingsEqualFold(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldEqualFold(FieldModelMappings, v))
}

// ModelMappingsContainsFold applies the ContainsFold predicate on the "model_mappings" field.
func ModelMappingsContainsFold(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldContainsFold(FieldModelMappings, v))
}

// AllowedChannelGroupsEQ applies the EQ predicate on the "allowed_channel_groups" field.
func AllowedChannelGroupsEQ(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldEQ(FieldAllowedChannelGroups, v))
}

// AllowedChannelGroupsNEQ applies the NEQ predicate on the "allowed_channel_groups" field.
func AllowedChannelGroupsNEQ(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldNEQ(FieldAllowedChannelGroups, v))
}

// AllowedChannelGroupsIn applies the In predicate on the "allowed_channel_groups" field.
func AllowedChannelGroupsIn(vs ...string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldIn(FieldAllowedChannelGroups, vs...))
}

// AllowedChannelGroupsNotIn applies the NotIn predicate on the "allowed_channel_groups" field.
func AllowedChannelGroupsNotIn(vs ...string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldNotIn(FieldAllowedChannelGroups, vs...))
}

// AllowedChannelGroupsGT applies the GT predicate on the "allowed_channel_groups" field.
func AllowedChannelGroupsGT(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldGT(FieldAllowedChannelGroups, v))
}

// AllowedChannelGroupsGTE applies the GTE predicate on the "allowed_channel_groups" field.
func AllowedChannelGroupsGTE(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldGTE(FieldAllowedChannelGroups, v))
}

// AllowedChannelGroupsLT applies the LT predicate on the "allowed_channel_groups" field.
func AllowedChannelGroupsLT(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldLT(FieldAllowedChannelGroups, v))
}

// AllowedChannelGroupsLTE applies the LTE predicate on the "allowed_channel_groups" field.
func AllowedChannelGroupsLTE(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldLTE(FieldAllowedChannelGroups, v))
}

// AllowedChannelGroupsContains applies the Contains predicate on the "allowed_channel_groups" field.
func AllowedChannelGroupsContains(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldContains(FieldAllowedChannelGroups, v))
}

// AllowedChannelGroupsHasPrefix applies the HasPrefix predicate on the "allowed_channel_groups" field.
func AllowedChannelGroupsHasPrefix(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldHasPrefix(FieldAllowedChannelGroups, v))
}

// AllowedChannelGroupsHasSuffix applies the HasSuffix predicate on the "allowed_channel_groups" field.
func AllowedChannelGroupsHasSuffix(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldHasSuffix(FieldAllowedChannelGroups, v))
}

// AllowedChannelGroupsEqualFold applies the EqualFold predicate on the "allowed_channel_groups" field.
func AllowedChannelGroupsEqualFold(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldEqualFold(FieldAllowedChannelGroups, v))
}

// AllowedChannelGroupsContainsFold applies the ContainsFold predicate on the "allowed_channel_groups" field.
func AllowedChannelGroupsContainsFold(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldContainsFold(FieldAllowedChannelGroups, v))
}

// RoutePathEQ applies the EQ predicate on the "route_path" field.
func RoutePathEQ(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldEQ(FieldRoutePath, v))
}

// RoutePathNEQ applies the NEQ predicate on the "route_path" field.
func RoutePathNEQ(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldNEQ(FieldRoutePath, v))
}

// RoutePathIn applies the In predicate on the "route_path" field.
func RoutePathIn(vs ...string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldIn(FieldRoutePath, vs...))
}

// RoutePathNotIn applies the NotIn predicate on the "route_path" field.
func RoutePathNotIn(vs ...string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldNotIn(FieldRoutePath, vs...))
}

// RoutePathGT applies the GT predicate on the "route_path" field.
func RoutePathGT(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldGT(FieldRoutePath, v))
}

// RoutePathGTE applies the GTE predicate on the "route_path" field.
func RoutePathGTE(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldGTE(FieldRoutePath, v))
}

// RoutePathLT applies the LT predicate on the "route_path" field.
func RoutePathLT(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldLT(FieldRoutePath, v))
}

// RoutePathLTE applies the LTE predicate on the "route_path" field.
func RoutePathLTE(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldLTE(FieldRoutePath, v))
}

// RoutePathContains applies the Contains predicate on the "route_path" field.
func RoutePathContains(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldContains(FieldRoutePath, v))
}

// RoutePathHasPrefix applies the HasPrefix predicate on the "route_path" field.
func RoutePathHasPrefix(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldHasPrefix(FieldRoutePath, v))
}

// RoutePathHasSuffix applies the HasSuffix predicate on the "route_path" field.
func RoutePathHasSuffix(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldHasSuffix(FieldRoutePath, v))
}

// RoutePathEqualFold applies the EqualFold predicate on the "route_path" field.
func RoutePathEqualFold(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldEqualFold(FieldRoutePath, v))
}

// RoutePathContainsFold applies the ContainsFold predicate on the "route_path" field.
func RoutePathContainsFold(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldContainsFold(FieldRoutePath, v))
}

// EndpointPathEQ applies the EQ predicate on the "endpoint_path" field.
func EndpointPathEQ(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldEQ(FieldEndpointPath, v))
}

// EndpointPathNEQ applies the NEQ predicate on the "endpoint_path" field.
func EndpointPathNEQ(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldNEQ(FieldEndpointPath, v))
}

// EndpointPathIn applies the In predicate on the "endpoint_path" field.
func EndpointPathIn(vs ...string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldIn(FieldEndpointPath, vs...))
}

// EndpointPathNotIn applies the NotIn predicate on the "endpoint_path" field.
func EndpointPathNotIn(vs ...string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldNotIn(FieldEndpointPath, vs...))
}

// EndpointPathGT applies the GT predicate on the "endpoint_path" field.
func EndpointPathGT(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldGT(FieldEndpointPath, v))
}

// EndpointPathGTE applies the GTE predicate on the "endpoint_path" field.
func EndpointPathGTE(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldGTE(FieldEndpointPath, v))
}

// EndpointPathLT applies the LT predicate on the "endpoint_path" field.
func EndpointPathLT(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldLT(FieldEndpointPath, v))
}

// EndpointPathLTE applies the LTE predicate on the "endpoint_path" field.
func EndpointPathLTE(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldLTE(FieldEndpointPath, v))
}

// EndpointPathContains applies the Contains predicate on the "endpoint_path" field.
func EndpointPathContains(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldContains(FieldEndpointPath, v))
}

// EndpointPathHasPrefix applies the HasPrefix predicate on the "endpoint_path" field.
func EndpointPathHasPrefix(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldHasPrefix(FieldEndpointPath, v))
}

// EndpointPathHasSuffix applies the HasSuffix predicate on the "endpoint_path" field.
func EndpointPathHasSuffix(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldHasSuffix(FieldEndpointPath, v))
}

// EndpointPathEqualFold applies the EqualFold predicate on the "endpoint_path" field.
func EndpointPathEqualFold(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldEqualFold(FieldEndpointPath, v))
}

// EndpointPathContainsFold applies the ContainsFold predicate on the "endpoint_path" field.
func EndpointPathContainsFold(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldContainsFold(FieldEndpointPath, v))
}

// UsageAutoIntervalEQ applies the EQ predicate on the "usage_auto_interval" field.
func UsageAutoIntervalEQ(v int) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldEQ(FieldUsageAutoInterval, v))
}

// UsageAutoIntervalNEQ applies the NEQ predicate on the "usage_auto_interval" field.
func UsageAutoIntervalNEQ(v int) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldNEQ(FieldUsageAutoInterval, v))
}

// UsageAutoIntervalIn applies the In predicate on the "usage_auto_interval" field.
func UsageAutoIntervalIn(vs ...int) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldIn(FieldUsageAutoInterval, vs...))
}

// UsageAutoIntervalNotIn applies the NotIn predicate on the "usage_auto_interval" field.
func UsageAutoIntervalNotIn(vs ...int) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldNotIn(FieldUsageAutoInterval, vs...))
}

// UsageAutoIntervalGT applies the GT predicate on the "usage_auto_interval" field.
func UsageAutoIntervalGT(v int) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldGT(FieldUsageAutoInterval, v))
}

// UsageAutoIntervalGTE applies the GTE predicate on the "usage_auto_interval" field.
func UsageAutoIntervalGTE(v int) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldGTE(FieldUsageAutoInterval, v))
}

// UsageAutoIntervalLT applies the LT predicate on the "usage_auto_interval" field.
func UsageAutoIntervalLT(v int) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldLT(FieldUsageAutoInterval, v))
}

// UsageAutoIntervalLTE applies the LTE predicate on the "usage_auto_interval" field.
func UsageAutoIntervalLTE(v int) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldLTE(FieldUsageAutoInterval, v))
}

// APIKeyFieldEQ applies the EQ predicate on the "api_key_field" field.
func APIKeyFieldEQ(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldEQ(FieldAPIKeyField, v))
}

// APIKeyFieldNEQ applies the NEQ predicate on the "api_key_field" field.
func APIKeyFieldNEQ(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldNEQ(FieldAPIKeyField, v))
}

// APIKeyFieldIn applies the In predicate on the "api_key_field" field.
func APIKeyFieldIn(vs ...string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldIn(FieldAPIKeyField, vs...))
}

// APIKeyFieldNotIn applies the NotIn predicate on the "api_key_field" field.
func APIKeyFieldNotIn(vs ...string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldNotIn(FieldAPIKeyField, vs...))
}

// APIKeyFieldGT applies the GT predicate on the "api_key_field" field.
func APIKeyFieldGT(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldGT(FieldAPIKeyField, v))
}

// APIKeyFieldGTE applies the GTE predicate on the "api_key_field" field.
func APIKeyFieldGTE(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldGTE(FieldAPIKeyField, v))
}

// APIKeyFieldLT applies the LT predicate on the "api_key_field" field.
func APIKeyFieldLT(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldLT(FieldAPIKeyField, v))
}

// APIKeyFieldLTE applies the LTE predicate on the "api_key_field" field.
func APIKeyFieldLTE(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldLTE(FieldAPIKeyField, v))
}

// APIKeyFieldContains applies the Contains predicate on the "api_key_field" field.
func APIKeyFieldContains(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldContains(FieldAPIKeyField, v))
}

// APIKeyFieldHasPrefix applies the HasPrefix predicate on the "api_key_field" field.
func APIKeyFieldHasPrefix(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldHasPrefix(FieldAPIKeyField, v))
}

// APIKeyFieldHasSuffix applies the HasSuffix predicate on the "api_key_field" field.
func APIKeyFieldHasSuffix(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldHasSuffix(FieldAPIKeyField, v))
}

// APIKeyFieldEqualFold applies the EqualFold predicate on the "api_key_field" field.
func APIKeyFieldEqualFold(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldEqualFold(FieldAPIKeyField, v))
}

// APIKeyFieldContainsFold applies the ContainsFold predicate on the "api_key_field" field.
func APIKeyFieldContainsFold(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldContainsFold(FieldAPIKeyField, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtContains applies the Contains predicate on the "created_at" field.
func CreatedAtContains(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldContains(FieldCreatedAt, v))
}

// CreatedAtHasPrefix applies the HasPrefix predicate on the "created_at" field.
func CreatedAtHasPrefix(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldHasPrefix(FieldCreatedAt, v))
}

// CreatedAtHasSuffix applies the HasSuffix predicate on the "created_at" field.
func CreatedAtHasSuffix(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldHasSuffix(FieldCreatedAt, v))
}

// CreatedAtEqualFold applies the EqualFold predicate on the "created_at" field.
func CreatedAtEqualFold(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldEqualFold(FieldCreatedAt, v))
}

// CreatedAtContainsFold applies the ContainsFold predicate on the "created_at" field.
func CreatedAtContainsFold(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldContainsFold(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtContains applies the Contains predicate on the "updated_at" field.
func UpdatedAtContains(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldContains(FieldUpdatedAt, v))
}

// UpdatedAtHasPrefix applies the HasPrefix predicate on the "updated_at" field.
func UpdatedAtHasPrefix(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldHasPrefix(FieldUpdatedAt, v))
}

// UpdatedAtHasSuffix applies the HasSuffix predicate on the "updated_at" field.
func UpdatedAtHasSuffix(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldHasSuffix(FieldUpdatedAt, v))
}

// UpdatedAtEqualFold applies the EqualFold predicate on the "updated_at" field.
func UpdatedAtEqualFold(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldEqualFold(FieldUpdatedAt, v))
}

// UpdatedAtContainsFold applies the ContainsFold predicate on the "updated_at" field.
func UpdatedAtContainsFold(v string) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.FieldContainsFold(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CcSwitchImportConfig) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CcSwitchImportConfig) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CcSwitchImportConfig) predicate.CcSwitchImportConfig {
	return predicate.CcSwitchImportConfig(sql.NotPredicates(p))
}
