// Code generated by ent, DO NOT EDIT.

package authfilequotasnapshotpoint

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/router-for-me/CLIProxyAPI/v6/internal/storage/postgres/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldEQ(FieldTenantID, v))
}

// RecordedAt applies equality check predicate on the "recorded_at" field. It's identical to RecordedAtEQ.
func RecordedAt(v time.Time) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldEQ(FieldRecordedAt, v))
}

// AuthIndex applies equality check predicate on the "auth_index" field. It's identical to AuthIndexEQ.
func AuthIndex(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldEQ(FieldAuthIndex, v))
}

// AuthSubjectID applies equality check predicate on the "auth_subject_id" field. It's identical to AuthSubjectIDEQ.
func AuthSubjectID(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldEQ(FieldAuthSubjectID, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldEQ(FieldProvider, v))
}

// QuotaKey applies equality check predicate on the "quota_key" field. It's identical to QuotaKeyEQ.
func QuotaKey(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldEQ(FieldQuotaKey, v))
}

// QuotaLabel applies equality check predicate on the "quota_label" field. It's identical to QuotaLabelEQ.
func QuotaLabel(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldEQ(FieldQuotaLabel, v))
}

// Percent applies equality check predicate on the "percent" field. It's identical to PercentEQ.
func Percent(v float64) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldEQ(FieldPercent, v))
}

// ResetAt applies equality check predicate on the "reset_at" field. It's identical to ResetAtEQ.
func ResetAt(v time.Time) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldEQ(FieldResetAt, v))
}

// WindowSeconds applies equality check predicate on the "window_seconds" field. It's identical to WindowSecondsEQ.
func WindowSeconds(v int64) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldEQ(FieldWindowSeconds, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldContainsFold(FieldTenantID, v))
}

// RecordedAtEQ applies the EQ predicate on the "recorded_at" field.
func RecordedAtEQ(v time.Time) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldEQ(FieldRecordedAt, v))
}

// RecordedAtNEQ applies the NEQ predicate on the "recorded_at" field.
func RecordedAtNEQ(v time.Time) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldNEQ(FieldRecordedAt, v))
}

// RecordedAtIn applies the In predicate on the "recorded_at" field.
func RecordedAtIn(vs ...time.Time) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldIn(FieldRecordedAt, vs...))
}

// RecordedAtNotIn applies the NotIn predicate on the "recorded_at" field.
func RecordedAtNotIn(vs ...time.Time) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldNotIn(FieldRecordedAt, vs...))
}

// RecordedAtGT applies the GT predicate on the "recorded_at" field.
func RecordedAtGT(v time.Time) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldGT(FieldRecordedAt, v))
}

// RecordedAtGTE applies the GTE predicate on the "recorded_at" field.
func RecordedAtGTE(v time.Time) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldGTE(FieldRecordedAt, v))
}

// RecordedAtLT applies the LT predicate on the "recorded_at" field.
func RecordedAtLT(v time.Time) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldLT(FieldRecordedAt, v))
}

// RecordedAtLTE applies the LTE predicate on the "recorded_at" field.
func RecordedAtLTE(v time.Time) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldLTE(FieldRecordedAt, v))
}

// AuthIndexEQ applies the EQ predicate on the "auth_index" field.
func AuthIndexEQ(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldEQ(FieldAuthIndex, v))
}

// AuthIndexNEQ applies the NEQ predicate on the "auth_index" field.
func AuthIndexNEQ(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldNEQ(FieldAuthIndex, v))
}

// AuthIndexIn applies the In predicate on the "auth_index" field.
func AuthIndexIn(vs ...string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldIn(FieldAuthIndex, vs...))
}

// AuthIndexNotIn applies the NotIn predicate on the "auth_index" field.
func AuthIndexNotIn(vs ...string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldNotIn(FieldAuthIndex, vs...))
}

// AuthIndexGT applies the GT predicate on the "auth_index" field.
func AuthIndexGT(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldGT(FieldAuthIndex, v))
}

// AuthIndexGTE applies the GTE predicate on the "auth_index" field.
func AuthIndexGTE(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldGTE(FieldAuthIndex, v))
}

// AuthIndexLT applies the LT predicate on the "auth_index" field.
func AuthIndexLT(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldLT(FieldAuthIndex, v))
}

// AuthIndexLTE applies the LTE predicate on the "auth_index" field.
func AuthIndexLTE(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldLTE(FieldAuthIndex, v))
}

// AuthIndexContains applies the Contains predicate on the "auth_index" field.
func AuthIndexContains(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldContains(FieldAuthIndex, v))
}

// AuthIndexHasPrefix applies the HasPrefix predicate on the "auth_index" field.
func AuthIndexHasPrefix(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldHasPrefix(FieldAuthIndex, v))
}

// AuthIndexHasSuffix applies the HasSuffix predicate on the "auth_index" field.
func AuthIndexHasSuffix(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldHasSuffix(FieldAuthIndex, v))
}

// AuthIndexEqualFold applies the EqualFold predicate on the "auth_index" field.
func AuthIndexEqualFold(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldEqualFold(FieldAuthIndex, v))
}

// AuthIndexContainsFold applies the ContainsFold predicate on the "auth_index" field.
func AuthIndexContainsFold(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldContainsFold(FieldAuthIndex, v))
}

// AuthSubjectIDEQ applies the EQ predicate on the "auth_subject_id" field.
func AuthSubjectIDEQ(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldEQ(FieldAuthSubjectID, v))
}

// AuthSubjectIDNEQ applies the NEQ predicate on the "auth_subject_id" field.
func AuthSubjectIDNEQ(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldNEQ(FieldAuthSubjectID, v))
}

// AuthSubjectIDIn applies the In predicate on the "auth_subject_id" field.
func AuthSubjectIDIn(vs ...string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldIn(FieldAuthSubjectID, vs...))
}

// AuthSubjectIDNotIn applies the NotIn predicate on the "auth_subject_id" field.
func AuthSubjectIDNotIn(vs ...string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldNotIn(FieldAuthSubjectID, vs...))
}

// AuthSubjectIDGT applies the GT predicate on the "auth_subject_id" field.
func AuthSubjectIDGT(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldGT(FieldAuthSubjectID, v))
}

// AuthSubjectIDGTE applies the GTE predicate on the "auth_subject_id" field.
func AuthSubjectIDGTE(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldGTE(FieldAuthSubjectID, v))
}

// AuthSubjectIDLT applies the LT predicate on the "auth_subject_id" field.
func AuthSubjectIDLT(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldLT(FieldAuthSubjectID, v))
}

// AuthSubjectIDLTE applies the LTE predicate on the "auth_subject_id" field.
func AuthSubjectIDLTE(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldLTE(FieldAuthSubjectID, v))
}

// AuthSubjectIDContains applies the Contains predicate on the "auth_subject_id" field.
func AuthSubjectIDContains(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldContains(FieldAuthSubjectID, v))
}

// AuthSubjectIDHasPrefix applies the HasPrefix predicate on the "auth_subject_id" field.
func AuthSubjectIDHasPrefix(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldHasPrefix(FieldAuthSubjectID, v))
}

// AuthSubjectIDHasSuffix applies the HasSuffix predicate on the "auth_subject_id" field.
func AuthSubjectIDHasSuffix(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldHasSuffix(FieldAuthSubjectID, v))
}

// AuthSubjectIDEqualFold applies the EqualFold predicate on the "auth_subject_id" field.
func AuthSubjectIDEqualFold(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldEqualFold(FieldAuthSubjectID, v))
}

// AuthSubjectIDContainsFold applies the ContainsFold predicate on the "auth_subject_id" field.
func AuthSubjectIDContainsFold(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldContainsFold(FieldAuthSubjectID, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldContainsFold(FieldProvider, v))
}

// QuotaKeyEQ applies the EQ predicate on the "quota_key" field.
func QuotaKeyEQ(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldEQ(FieldQuotaKey, v))
}

// QuotaKeyNEQ applies the NEQ predicate on the "quota_key" field.
func QuotaKeyNEQ(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldNEQ(FieldQuotaKey, v))
}

// QuotaKeyIn applies the In predicate on the "quota_key" field.
func QuotaKeyIn(vs ...string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldIn(FieldQuotaKey, vs...))
}

// QuotaKeyNotIn applies the NotIn predicate on the "quota_key" field.
func QuotaKeyNotIn(vs ...string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldNotIn(FieldQuotaKey, vs...))
}

// QuotaKeyGT applies the GT predicate on the "quota_key" field.
func QuotaKeyGT(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldGT(FieldQuotaKey, v))
}

// QuotaKeyGTE applies the GTE predicate on the "quota_key" field.
func QuotaKeyGTE(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldGTE(FieldQuotaKey, v))
}

// QuotaKeyLT applies the LT predicate on the "quota_key" field.
func QuotaKeyLT(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldLT(FieldQuotaKey, v))
}

// QuotaKeyLTE applies the LTE predicate on the "quota_key" field.
func QuotaKeyLTE(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldLTE(FieldQuotaKey, v))
}

// QuotaKeyContains applies the Contains predicate on the "quota_key" field.
func QuotaKeyContains(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldContains(FieldQuotaKey, v))
}

// QuotaKeyHasPrefix applies the HasPrefix predicate on the "quota_key" field.
func QuotaKeyHasPrefix(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldHasPrefix(FieldQuotaKey, v))
}

// QuotaKeyHasSuffix applies the HasSuffix predicate on the "quota_key" field.
func QuotaKeyHasSuffix(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldHasSuffix(FieldQuotaKey, v))
}

// QuotaKeyEqualFold applies the EqualFold predicate on the "quota_key" field.
func QuotaKeyEqualFold(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldEqualFold(FieldQuotaKey, v))
}

// QuotaKeyContainsFold applies the ContainsFold predicate on the "quota_key" field.
func QuotaKeyContainsFold(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldContainsFold(FieldQuotaKey, v))
}

// QuotaLabelEQ applies the EQ predicate on the "quota_label" field.
func QuotaLabelEQ(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldEQ(FieldQuotaLabel, v))
}

// QuotaLabelNEQ applies the NEQ predicate on the "quota_label" field.
func QuotaLabelNEQ(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldNEQ(FieldQuotaLabel, v))
}

// QuotaLabelIn applies the In predicate on the "quota_label" field.
func QuotaLabelIn(vs ...string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldIn(FieldQuotaLabel, vs...))
}

// QuotaLabelNotIn applies the NotIn predicate on the "quota_label" field.
func QuotaLabelNotIn(vs ...string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldNotIn(FieldQuotaLabel, vs...))
}

// QuotaLabelGT applies the GT predicate on the "quota_label" field.
func QuotaLabelGT(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldGT(FieldQuotaLabel, v))
}

// QuotaLabelGTE applies the GTE predicate on the "quota_label" field.
func QuotaLabelGTE(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldGTE(FieldQuotaLabel, v))
}

// QuotaLabelLT applies the LT predicate on the "quota_label" field.
func QuotaLabelLT(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldLT(FieldQuotaLabel, v))
}

// QuotaLabelLTE applies the LTE predicate on the "quota_label" field.
func QuotaLabelLTE(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldLTE(FieldQuotaLabel, v))
}

// QuotaLabelContains applies the Contains predicate on the "quota_label" field.
func QuotaLabelContains(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldContains(FieldQuotaLabel, v))
}

// QuotaLabelHasPrefix applies the HasPrefix predicate on the "quota_label" field.
func QuotaLabelHasPrefix(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldHasPrefix(FieldQuotaLabel, v))
}

// QuotaLabelHasSuffix applies the HasSuffix predicate on the "quota_label" field.
func QuotaLabelHasSuffix(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldHasSuffix(FieldQuotaLabel, v))
}

// QuotaLabelEqualFold applies the EqualFold predicate on the "quota_label" field.
func QuotaLabelEqualFold(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldEqualFold(FieldQuotaLabel, v))
}

// QuotaLabelContainsFold applies the ContainsFold predicate on the "quota_label" field.
func QuotaLabelContainsFold(v string) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldContainsFold(FieldQuotaLabel, v))
}

// PercentEQ applies the EQ predicate on the "percent" field.
func PercentEQ(v float64) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldEQ(FieldPercent, v))
}

// PercentNEQ applies the NEQ predicate on the "percent" field.
func PercentNEQ(v float64) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldNEQ(FieldPercent, v))
}

// PercentIn applies the In predicate on the "percent" field.
func PercentIn(vs ...float64) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldIn(FieldPercent, vs...))
}

// PercentNotIn applies the NotIn predicate on the "percent" field.
func PercentNotIn(vs ...float64) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldNotIn(FieldPercent, vs...))
}

// PercentGT applies the GT predicate on the "percent" field.
func PercentGT(v float64) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldGT(FieldPercent, v))
}

// PercentGTE applies the GTE predicate on the "percent" field.
func PercentGTE(v float64) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldGTE(FieldPercent, v))
}

// PercentLT applies the LT predicate on the "percent" field.
func PercentLT(v float64) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldLT(FieldPercent, v))
}

// PercentLTE applies the LTE predicate on the "percent" field.
func PercentLTE(v float64) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldLTE(FieldPercent, v))
}

// PercentIsNil applies the IsNil predicate on the "percent" field.
func PercentIsNil() predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldIsNull(FieldPercent))
}

// PercentNotNil applies the NotNil predicate on the "percent" field.
func PercentNotNil() predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldNotNull(FieldPercent))
}

// ResetAtEQ applies the EQ predicate on the "reset_at" field.
func ResetAtEQ(v time.Time) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldEQ(FieldResetAt, v))
}

// ResetAtNEQ applies the NEQ predicate on the "reset_at" field.
func ResetAtNEQ(v time.Time) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldNEQ(FieldResetAt, v))
}

// ResetAtIn applies the In predicate on the "reset_at" field.
func ResetAtIn(vs ...time.Time) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldIn(FieldResetAt, vs...))
}

// ResetAtNotIn applies the NotIn predicate on the "reset_at" field.
func ResetAtNotIn(vs ...time.Time) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldNotIn(FieldResetAt, vs...))
}

// ResetAtGT applies the GT predicate on the "reset_at" field.
func ResetAtGT(v time.Time) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldGT(FieldResetAt, v))
}

// ResetAtGTE applies the GTE predicate on the "reset_at" field.
func ResetAtGTE(v time.Time) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldGTE(FieldResetAt, v))
}

// ResetAtLT applies the LT predicate on the "reset_at" field.
func ResetAtLT(v time.Time) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldLT(FieldResetAt, v))
}

// ResetAtLTE applies the LTE predicate on the "reset_at" field.
func ResetAtLTE(v time.Time) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldLTE(FieldResetAt, v))
}

// ResetAtIsNil applies the IsNil predicate on the "reset_at" field.
func ResetAtIsNil() predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldIsNull(FieldResetAt))
}

// ResetAtNotNil applies the NotNil predicate on the "reset_at" field.
func ResetAtNotNil() predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldNotNull(FieldResetAt))
}

// WindowSecondsEQ applies the EQ predicate on the "window_seconds" field.
func WindowSecondsEQ(v int64) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldEQ(FieldWindowSeconds, v))
}

// WindowSecondsNEQ applies the NEQ predicate on the "window_seconds" field.
func WindowSecondsNEQ(v int64) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldNEQ(FieldWindowSeconds, v))
}

// WindowSecondsIn applies the In predicate on the "window_seconds" field.
func WindowSecondsIn(vs ...int64) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldIn(FieldWindowSeconds, vs...))
}

// WindowSecondsNotIn applies the NotIn predicate on the "window_seconds" field.
func WindowSecondsNotIn(vs ...int64) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldNotIn(FieldWindowSeconds, vs...))
}

// WindowSecondsGT applies the GT predicate on the "window_seconds" field.
func WindowSecondsGT(v int64) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldGT(FieldWindowSeconds, v))
}

// WindowSecondsGTE applies the GTE predicate on the "window_seconds" field.
func WindowSecondsGTE(v int64) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldGTE(FieldWindowSeconds, v))
}

// WindowSecondsLT applies the LT predicate on the "window_seconds" field.
func WindowSecondsLT(v int64) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldLT(FieldWindowSeconds, v))
}

// WindowSecondsLTE applies the LTE predicate on the "window_seconds" field.
func WindowSecondsLTE(v int64) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.FieldLTE(FieldWindowSeconds, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AuthFileQuotaSnapshotPoint) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AuthFileQuotaSnapshotPoint) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AuthFileQuotaSnapshotPoint) predicate.AuthFileQuotaSnapshotPoint {
	return predicate.AuthFileQuotaSnapshotPoint(sql.NotPredicates(p))
}
