// Code generated by ent, DO NOT EDIT.

package modelopenroutersyncstate

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the modelopenroutersyncstate type in the database.
	Label = "model_openrouter_sync_state"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldIntervalMinutes holds the string denoting the interval_minutes field in the database.
	FieldIntervalMinutes = "interval_minutes"
	// FieldLastSyncAt holds the string denoting the last_sync_at field in the database.
	FieldLastSyncAt = "last_sync_at"
	// FieldLastSuccessAt holds the string denoting the last_success_at field in the database.
	FieldLastSuccessAt = "last_success_at"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldLastSeen holds the string denoting the last_seen field in the database.
	FieldLastSeen = "last_seen"
	// FieldLastAdded holds the string denoting the last_added field in the database.
	FieldLastAdded = "last_added"
	// FieldLastUpdated holds the string denoting the last_updated field in the database.
	FieldLastUpdated = "last_updated"
	// FieldLastSkipped holds the string denoting the last_skipped field in the database.
	FieldLastSkipped = "last_skipped"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the modelopenroutersyncstate in the database.
	Table = "model_openrouter_sync_state"
)

// Columns holds all SQL columns for modelopenroutersyncstate fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldEnabled,
	FieldIntervalMinutes,
	FieldLastSyncAt,
	FieldLastSuccessAt,
	FieldLastError,
	FieldLastSeen,
	FieldLastAdded,
	FieldLastUpdated,
	FieldLastSkipped,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTenantID holds the default value on creation for the "tenant_id" field.
	DefaultTenantID string
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled int
	// DefaultIntervalMinutes holds the default value on creation for the "interval_minutes" field.
	DefaultIntervalMinutes int
	// DefaultLastSyncAt holds the default value on creation for the "last_sync_at" field.
	DefaultLastSyncAt string
	// DefaultLastSuccessAt holds the default value on creation for the "last_success_at" field.
	DefaultLastSuccessAt string
	// DefaultLastError holds the default value on creation for the "last_error" field.
	DefaultLastError string
	// DefaultLastSeen holds the default value on creation for the "last_seen" field.
	DefaultLastSeen int
	// DefaultLastAdded holds the default value on creation for the "last_added" field.
	DefaultLastAdded int
	// DefaultLastUpdated holds the default value on creation for the "last_updated" field.
	DefaultLastUpdated int
	// DefaultLastSkipped holds the default value on creation for the "last_skipped" field.
	DefaultLastSkipped int
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID int
)

// OrderOption defines the ordering options for the ModelOpenrouterSyncState queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByIntervalMinutes orders the results by the interval_minutes field.
func ByIntervalMinutes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIntervalMinutes, opts...).ToFunc()
}

// ByLastSyncAt orders the results by the last_sync_at field.
func ByLastSyncAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSyncAt, opts...).ToFunc()
}

// ByLastSuccessAt orders the results by the last_success_at field.
func ByLastSuccessAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSuccessAt, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByLastSeen orders the results by the last_seen field.
func ByLastSeen(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSeen, opts...).ToFunc()
}

// ByLastAdded orders the results by the last_added field.
func ByLastAdded(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastAdded, opts...).ToFunc()
}

// ByLastUpdated orders the results by the last_updated field.
func ByLastUpdated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastUpdated, opts...).ToFunc()
}

// ByLastSkipped orders the results by the last_skipped field.
func ByLastSkipped(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSkipped, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
