// Code generated by ent, DO NOT EDIT.

package modelownerpreset

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the modelownerpreset type in the database.
	Label = "model_owner_preset"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldValue holds the string denoting the value field in the database.
	FieldValue = "value"
	// FieldLabel holds the string denoting the label field in the database.
	FieldLabel = "label"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the modelownerpreset in the database.
	Table = "model_owner_presets"
)

// Columns holds all SQL columns for modelownerpreset fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldValue,
	FieldLabel,
	FieldDescription,
	FieldEnabled,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTenantID holds the default value on creation for the "tenant_id" field.
	DefaultTenantID string
	// DefaultLabel holds the default value on creation for the "label" field.
	DefaultLabel string
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled int
)

// OrderOption defines the ordering options for the ModelOwnerPreset queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByValue orders the results by the value field.
func ByValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValue, opts...).ToFunc()
}

// ByLabel orders the results by the label field.
func ByLabel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLabel, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
