// Code generated by ent, DO NOT EDIT.

package authgroupmodelownermapping

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the authgroupmodelownermapping type in the database.
	Label = "auth_group_model_owner_mapping"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldAuthGroup holds the string denoting the auth_group field in the database.
	FieldAuthGroup = "auth_group"
	// FieldOwner holds the string denoting the owner field in the database.
	FieldOwner = "owner"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the authgroupmodelownermapping in the database.
	Table = "auth_group_model_owner_mappings"
)

// Columns holds all SQL columns for authgroupmodelownermapping fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldAuthGroup,
	FieldOwner,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTenantID holds the default value on creation for the "tenant_id" field.
	DefaultTenantID string
	// DefaultOwner holds the default value on creation for the "owner" field.
	DefaultOwner string
)

// OrderOption defines the ordering options for the AuthGroupModelOwnerMapping queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByAuthGroup orders the results by the auth_group field.
func ByAuthGroup(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthGroup, opts...).ToFunc()
}

// ByOwner orders the results by the owner field.
func ByOwner(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwner, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
