// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/router-for-me/CLIProxyAPI/v6/internal/storage/postgres/ent/auditlog"
	"github.com/router-for-me/CLIProxyAPI/v6/internal/storage/postgres/ent/predicate"
)

// AuditLogUpdate is the builder for updating AuditLog entities.
type AuditLogUpdate struct {
	config
	hooks    []Hook
	mutation *AuditLogMutation
}

// Where appends a list predicates to the AuditLogUpdate builder.
func (_u *AuditLogUpdate) Where(ps ...predicate.AuditLog) *AuditLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *AuditLogUpdate) SetTenantID(v string) *AuditLogUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableTenantID(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// ClearTenantID clears the value of the "tenant_id" field.
func (_u *AuditLogUpdate) ClearTenantID() *AuditLogUpdate {
	_u.mutation.ClearTenantID()
	return _u
}

// SetActorKind sets the "actor_kind" field.
func (_u *AuditLogUpdate) SetActorKind(v string) *AuditLogUpdate {
	_u.mutation.SetActorKind(v)
	return _u
}

// SetNillableActorKind sets the "actor_kind" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableActorKind(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetActorKind(*v)
	}
	return _u
}

// SetActorUserID sets the "actor_user_id" field.
func (_u *AuditLogUpdate) SetActorUserID(v string) *AuditLogUpdate {
	_u.mutation.SetActorUserID(v)
	return _u
}

// SetNillableActorUserID sets the "actor_user_id" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableActorUserID(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetActorUserID(*v)
	}
	return _u
}

// ClearActorUserID clears the value of the "actor_user_id" field.
func (_u *AuditLogUpdate) ClearActorUserID() *AuditLogUpdate {
	_u.mutation.ClearActorUserID()
	return _u
}

// SetActorSessionID sets the "actor_session_id" field.
func (_u *AuditLogUpdate) SetActorSessionID(v string) *AuditLogUpdate {
	_u.mutation.SetActorSessionID(v)
	return _u
}

// SetNillableActorSessionID sets the "actor_session_id" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableActorSessionID(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetActorSessionID(*v)
	}
	return _u
}

// ClearActorSessionID clears the value of the "actor_session_id" field.
func (_u *AuditLogUpdate) ClearActorSessionID() *AuditLogUpdate {
	_u.mutation.ClearActorSessionID()
	return _u
}

// SetAction sets the "action" field.
func (_u *AuditLogUpdate) SetAction(v string) *AuditLogUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableAction(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *AuditLogUpdate) SetResourceType(v string) *AuditLogUpdate {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableResourceType(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *AuditLogUpdate) SetResourceID(v string) *AuditLogUpdate {
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableResourceID(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// SetResult sets the "result" field.
func (_u *AuditLogUpdate) SetResult(v string) *AuditLogUpdate {
	_u.mutation.SetResult(v)
	return _u
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableResult(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetResult(*v)
	}
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *AuditLogUpdate) SetRequestID(v string) *AuditLogUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableRequestID(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetChanges sets the "changes" field.
func (_u *AuditLogUpdate) SetChanges(v map[string]interface{}) *AuditLogUpdate {
	_u.mutation.SetChanges(v)
	return _u
}

// ClearChanges clears the value of the "changes" field.
func (_u *AuditLogUpdate) ClearChanges() *AuditLogUpdate {
	_u.mutation.ClearChanges()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AuditLogUpdate) SetCreatedAt(v time.Time) *AuditLogUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableCreatedAt(v *time.Time) *AuditLogUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the AuditLogMutation object of the builder.
func (_u *AuditLogUpdate) Mutation() *AuditLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuditLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuditLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AuditLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(auditlog.Table, auditlog.Columns, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(auditlog.FieldTenantID, field.TypeString, value)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(auditlog.FieldTenantID, field.TypeString)
	}
	if value, ok := _u.mutation.ActorKind(); ok {
		_spec.SetField(auditlog.FieldActorKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActorUserID(); ok {
		_spec.SetField(auditlog.FieldActorUserID, field.TypeString, value)
	}
	if _u.mutation.ActorUserIDCleared() {
		_spec.ClearField(auditlog.FieldActorUserID, field.TypeString)
	}
	if value, ok := _u.mutation.ActorSessionID(); ok {
		_spec.SetField(auditlog.FieldActorSessionID, field.TypeString, value)
	}
	if _u.mutation.ActorSessionIDCleared() {
		_spec.ClearField(auditlog.FieldActorSessionID, field.TypeString)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(auditlog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(auditlog.FieldResourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(auditlog.FieldResourceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Result(); ok {
		_spec.SetField(auditlog.FieldResult, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(auditlog.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Changes(); ok {
		_spec.SetField(auditlog.FieldChanges, field.TypeJSON, value)
	}
	if _u.mutation.ChangesCleared() {
		_spec.ClearField(auditlog.FieldChanges, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(auditlog.FieldCreatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuditLogUpdateOne is the builder for updating a single AuditLog entity.
type AuditLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuditLogMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *AuditLogUpdateOne) SetTenantID(v string) *AuditLogUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableTenantID(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// ClearTenantID clears the value of the "tenant_id" field.
func (_u *AuditLogUpdateOne) ClearTenantID() *AuditLogUpdateOne {
	_u.mutation.ClearTenantID()
	return _u
}

// SetActorKind sets the "actor_kind" field.
func (_u *AuditLogUpdateOne) SetActorKind(v string) *AuditLogUpdateOne {
	_u.mutation.SetActorKind(v)
	return _u
}

// SetNillableActorKind sets the "actor_kind" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableActorKind(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetActorKind(*v)
	}
	return _u
}

// SetActorUserID sets the "actor_user_id" field.
func (_u *AuditLogUpdateOne) SetActorUserID(v string) *AuditLogUpdateOne {
	_u.mutation.SetActorUserID(v)
	return _u
}

// SetNillableActorUserID sets the "actor_user_id" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableActorUserID(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetActorUserID(*v)
	}
	return _u
}

// ClearActorUserID clears the value of the "actor_user_id" field.
func (_u *AuditLogUpdateOne) ClearActorUserID() *AuditLogUpdateOne {
	_u.mutation.ClearActorUserID()
	return _u
}

// SetActorSessionID sets the "actor_session_id" field.
func (_u *AuditLogUpdateOne) SetActorSessionID(v string) *AuditLogUpdateOne {
	_u.mutation.SetActorSessionID(v)
	return _u
}

// SetNillableActorSessionID sets the "actor_session_id" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableActorSessionID(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetActorSessionID(*v)
	}
	return _u
}

// ClearActorSessionID clears the value of the "actor_session_id" field.
func (_u *AuditLogUpdateOne) ClearActorSessionID() *AuditLogUpdateOne {
	_u.mutation.ClearActorSessionID()
	return _u
}

// SetAction sets the "action" field.
func (_u *AuditLogUpdateOne) SetAction(v string) *AuditLogUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableAction(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *AuditLogUpdateOne) SetResourceType(v string) *AuditLogUpdateOne {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableResourceType(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *AuditLogUpdateOne) SetResourceID(v string) *AuditLogUpdateOne {
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableResourceID(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// SetResult sets the "result" field.
func (_u *AuditLogUpdateOne) SetResult(v string) *AuditLogUpdateOne {
	_u.mutation.SetResult(v)
	return _u
}

// SetNillableResult sets the "result" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableResult(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetResult(*v)
	}
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *AuditLogUpdateOne) SetRequestID(v string) *AuditLogUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableRequestID(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetChanges sets the "changes" field.
func (_u *AuditLogUpdateOne) SetChanges(v map[string]interface{}) *AuditLogUpdateOne {
	_u.mutation.SetChanges(v)
	return _u
}

// ClearChanges clears the value of the "changes" field.
func (_u *AuditLogUpdateOne) ClearChanges() *AuditLogUpdateOne {
	_u.mutation.ClearChanges()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AuditLogUpdateOne) SetCreatedAt(v time.Time) *AuditLogUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableCreatedAt(v *time.Time) *AuditLogUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the AuditLogMutation object of the builder.
func (_u *AuditLogUpdateOne) Mutation() *AuditLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the AuditLogUpdate builder.
func (_u *AuditLogUpdateOne) Where(ps ...predicate.AuditLog) *AuditLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuditLogUpdateOne) Select(field string, fields ...string) *AuditLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuditLog entity.
func (_u *AuditLogUpdateOne) Save(ctx context.Context) (*AuditLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditLogUpdateOne) SaveX(ctx context.Context) *AuditLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuditLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AuditLogUpdateOne) sqlSave(ctx context.Context) (_node *AuditLog, err error) {
	_spec := sqlgraph.NewUpdateSpec(auditlog.Table, auditlog.Columns, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuditLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, auditlog.FieldID)
		for _, f := range fields {
			if !auditlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != auditlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(auditlog.FieldTenantID, field.TypeString, value)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(auditlog.FieldTenantID, field.TypeString)
	}
	if value, ok := _u.mutation.ActorKind(); ok {
		_spec.SetField(auditlog.FieldActorKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActorUserID(); ok {
		_spec.SetField(auditlog.FieldActorUserID, field.TypeString, value)
	}
	if _u.mutation.ActorUserIDCleared() {
		_spec.ClearField(auditlog.FieldActorUserID, field.TypeString)
	}
	if value, ok := _u.mutation.ActorSessionID(); ok {
		_spec.SetField(auditlog.FieldActorSessionID, field.TypeString, value)
	}
	if _u.mutation.ActorSessionIDCleared() {
		_spec.ClearField(auditlog.FieldActorSessionID, field.TypeString)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(auditlog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(auditlog.FieldResourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(auditlog.FieldResourceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Result(); ok {
		_spec.SetField(auditlog.FieldResult, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(auditlog.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Changes(); ok {
		_spec.SetField(auditlog.FieldChanges, field.TypeJSON, value)
	}
	if _u.mutation.ChangesCleared() {
		_spec.ClearField(auditlog.FieldChanges, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(auditlog.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &AuditLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
