// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/router-for-me/CLIProxyAPI/v6/internal/storage/postgres/ent/authsubjectquotacycle"
)

// AuthSubjectQuotaCycle is the model entity for the AuthSubjectQuotaCycle schema.
type AuthSubjectQuotaCycle struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID string `json:"tenant_id,omitempty"`
	// SubjectID holds the value of the "subject_id" field.
	SubjectID string `json:"subject_id,omitempty"`
	// AuthIndex holds the value of the "auth_index" field.
	AuthIndex string `json:"auth_index,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// QuotaKey holds the value of the "quota_key" field.
	QuotaKey string `json:"quota_key,omitempty"`
	// CycleStartAt holds the value of the "cycle_start_at" field.
	CycleStartAt time.Time `json:"cycle_start_at,omitempty"`
	// ResetAt holds the value of the "reset_at" field.
	ResetAt time.Time `json:"reset_at,omitempty"`
	// WindowSeconds holds the value of the "window_seconds" field.
	WindowSeconds int64 `json:"window_seconds,omitempty"`
	// LastVerifiedAt holds the value of the "last_verified_at" field.
	LastVerifiedAt time.Time `json:"last_verified_at,omitempty"`
	selectValues   sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AuthSubjectQuotaCycle) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case authsubjectquotacycle.FieldID, authsubjectquotacycle.FieldWindowSeconds:
			values[i] = new(sql.NullInt64)
		case authsubjectquotacycle.FieldTenantID, authsubjectquotacycle.FieldSubjectID, authsubjectquotacycle.FieldAuthIndex, authsubjectquotacycle.FieldProvider, authsubjectquotacycle.FieldQuotaKey:
			values[i] = new(sql.NullString)
		case authsubjectquotacycle.FieldCycleStartAt, authsubjectquotacycle.FieldResetAt, authsubjectquotacycle.FieldLastVerifiedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AuthSubjectQuotaCycle fields.
func (_m *AuthSubjectQuotaCycle) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case authsubjectquotacycle.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case authsubjectquotacycle.FieldTenantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = value.String
			}
		case authsubjectquotacycle.FieldSubjectID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subject_id", values[i])
			} else if value.Valid {
				_m.SubjectID = value.String
			}
		case authsubjectquotacycle.FieldAuthIndex:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field auth_index", values[i])
			} else if value.Valid {
				_m.AuthIndex = value.String
			}
		case authsubjectquotacycle.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case authsubjectquotacycle.FieldQuotaKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field quota_key", values[i])
			} else if value.Valid {
				_m.QuotaKey = value.String
			}
		case authsubjectquotacycle.FieldCycleStartAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field cycle_start_at", values[i])
			} else if value.Valid {
				_m.CycleStartAt = value.Time
			}
		case authsubjectquotacycle.FieldResetAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field reset_at", values[i])
			} else if value.Valid {
				_m.ResetAt = value.Time
			}
		case authsubjectquotacycle.FieldWindowSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field window_seconds", values[i])
			} else if value.Valid {
				_m.WindowSeconds = value.Int64
			}
		case authsubjectquotacycle.FieldLastVerifiedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_verified_at", values[i])
			} else if value.Valid {
				_m.LastVerifiedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AuthSubjectQuotaCycle.
// This includes values selected through modifiers, order, etc.
func (_m *AuthSubjectQuotaCycle) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AuthSubjectQuotaCycle.
// Note that you need to call AuthSubjectQuotaCycle.Unwrap() before calling this method if this AuthSubjectQuotaCycle
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AuthSubjectQuotaCycle) Update() *AuthSubjectQuotaCycleUpdateOne {
	return NewAuthSubjectQuotaCycleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AuthSubjectQuotaCycle entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AuthSubjectQuotaCycle) Unwrap() *AuthSubjectQuotaCycle {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AuthSubjectQuotaCycle is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AuthSubjectQuotaCycle) String() string {
	var builder strings.Builder
	builder.WriteString("AuthSubjectQuotaCycle(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(_m.TenantID)
	builder.WriteString(", ")
	builder.WriteString("subject_id=")
	builder.WriteString(_m.SubjectID)
	builder.WriteString(", ")
	builder.WriteString("auth_index=")
	builder.WriteString(_m.AuthIndex)
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("quota_key=")
	builder.WriteString(_m.QuotaKey)
	builder.WriteString(", ")
	builder.WriteString("cycle_start_at=")
	builder.WriteString(_m.CycleStartAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("reset_at=")
	builder.WriteString(_m.ResetAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("window_seconds=")
	builder.WriteString(fmt.Sprintf("%v", _m.WindowSeconds))
	builder.WriteString(", ")
	builder.WriteString("last_verified_at=")
	builder.WriteString(_m.LastVerifiedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AuthSubjectQuotaCycles is a parsable slice of AuthSubjectQuotaCycle.
type AuthSubjectQuotaCycles []*AuthSubjectQuotaCycle
