// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/router-for-me/CLIProxyAPI/v6/internal/storage/postgres/ent/authfilequotasnapshotpoint"
)

// AuthFileQuotaSnapshotPointCreate is the builder for creating a AuthFileQuotaSnapshotPoint entity.
type AuthFileQuotaSnapshotPointCreate struct {
	config
	mutation *AuthFileQuotaSnapshotPointMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *AuthFileQuotaSnapshotPointCreate) SetTenantID(v string) *AuthFileQuotaSnapshotPointCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *AuthFileQuotaSnapshotPointCreate) SetNillableTenantID(v *string) *AuthFileQuotaSnapshotPointCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetRecordedAt sets the "recorded_at" field.
func (_c *AuthFileQuotaSnapshotPointCreate) SetRecordedAt(v time.Time) *AuthFileQuotaSnapshotPointCreate {
	_c.mutation.SetRecordedAt(v)
	return _c
}

// SetAuthIndex sets the "auth_index" field.
func (_c *AuthFileQuotaSnapshotPointCreate) SetAuthIndex(v string) *AuthFileQuotaSnapshotPointCreate {
	_c.mutation.SetAuthIndex(v)
	return _c
}

// SetAuthSubjectID sets the "auth_subject_id" field.
func (_c *AuthFileQuotaSnapshotPointCreate) SetAuthSubjectID(v string) *AuthFileQuotaSnapshotPointCreate {
	_c.mutation.SetAuthSubjectID(v)
	return _c
}

// SetNillableAuthSubjectID sets the "auth_subject_id" field if the given value is not nil.
func (_c *AuthFileQuotaSnapshotPointCreate) SetNillableAuthSubjectID(v *string) *AuthFileQuotaSnapshotPointCreate {
	if v != nil {
		_c.SetAuthSubjectID(*v)
	}
	return _c
}

// SetProvider sets the "provider" field.
func (_c *AuthFileQuotaSnapshotPointCreate) SetProvider(v string) *AuthFileQuotaSnapshotPointCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *AuthFileQuotaSnapshotPointCreate) SetNillableProvider(v *string) *AuthFileQuotaSnapshotPointCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetQuotaKey sets the "quota_key" field.
func (_c *AuthFileQuotaSnapshotPointCreate) SetQuotaKey(v string) *AuthFileQuotaSnapshotPointCreate {
	_c.mutation.SetQuotaKey(v)
	return _c
}

// SetQuotaLabel sets the "quota_label" field.
func (_c *AuthFileQuotaSnapshotPointCreate) SetQuotaLabel(v string) *AuthFileQuotaSnapshotPointCreate {
	_c.mutation.SetQuotaLabel(v)
	return _c
}

// SetNillableQuotaLabel sets the "quota_label" field if the given value is not nil.
func (_c *AuthFileQuotaSnapshotPointCreate) SetNillableQuotaLabel(v *string) *AuthFileQuotaSnapshotPointCreate {
	if v != nil {
		_c.SetQuotaLabel(*v)
	}
	return _c
}

// SetPercent sets the "percent" field.
func (_c *AuthFileQuotaSnapshotPointCreate) SetPercent(v float64) *AuthFileQuotaSnapshotPointCreate {
	_c.mutation.SetPercent(v)
	return _c
}

// SetNillablePercent sets the "percent" field if the given value is not nil.
func (_c *AuthFileQuotaSnapshotPointCreate) SetNillablePercent(v *float64) *AuthFileQuotaSnapshotPointCreate {
	if v != nil {
		_c.SetPercent(*v)
	}
	return _c
}

// SetResetAt sets the "reset_at" field.
func (_c *AuthFileQuotaSnapshotPointCreate) SetResetAt(v time.Time) *AuthFileQuotaSnapshotPointCreate {
	_c.mutation.SetResetAt(v)
	return _c
}

// SetNillableResetAt sets the "reset_at" field if the given value is not nil.
func (_c *AuthFileQuotaSnapshotPointCreate) SetNillableResetAt(v *time.Time) *AuthFileQuotaSnapshotPointCreate {
	if v != nil {
		_c.SetResetAt(*v)
	}
	return _c
}

// SetWindowSeconds sets the "window_seconds" field.
func (_c *AuthFileQuotaSnapshotPointCreate) SetWindowSeconds(v int64) *AuthFileQuotaSnapshotPointCreate {
	_c.mutation.SetWindowSeconds(v)
	return _c
}

// SetNillableWindowSeconds sets the "window_seconds" field if the given value is not nil.
func (_c *AuthFileQuotaSnapshotPointCreate) SetNillableWindowSeconds(v *int64) *AuthFileQuotaSnapshotPointCreate {
	if v != nil {
		_c.SetWindowSeconds(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AuthFileQuotaSnapshotPointCreate) SetID(v int64) *AuthFileQuotaSnapshotPointCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the AuthFileQuotaSnapshotPointMutation object of the builder.
func (_c *AuthFileQuotaSnapshotPointCreate) Mutation() *AuthFileQuotaSnapshotPointMutation {
	return _c.mutation
}

// Save creates the AuthFileQuotaSnapshotPoint in the database.
func (_c *AuthFileQuotaSnapshotPointCreate) Save(ctx context.Context) (*AuthFileQuotaSnapshotPoint, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuthFileQuotaSnapshotPointCreate) SaveX(ctx context.Context) *AuthFileQuotaSnapshotPoint {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthFileQuotaSnapshotPointCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthFileQuotaSnapshotPointCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuthFileQuotaSnapshotPointCreate) defaults() {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := authfilequotasnapshotpoint.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.AuthSubjectID(); !ok {
		v := authfilequotasnapshotpoint.DefaultAuthSubjectID
		_c.mutation.SetAuthSubjectID(v)
	}
	if _, ok := _c.mutation.Provider(); !ok {
		v := authfilequotasnapshotpoint.DefaultProvider
		_c.mutation.SetProvider(v)
	}
	if _, ok := _c.mutation.QuotaLabel(); !ok {
		v := authfilequotasnapshotpoint.DefaultQuotaLabel
		_c.mutation.SetQuotaLabel(v)
	}
	if _, ok := _c.mutation.WindowSeconds(); !ok {
		v := authfilequotasnapshotpoint.DefaultWindowSeconds
		_c.mutation.SetWindowSeconds(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuthFileQuotaSnapshotPointCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "AuthFileQuotaSnapshotPoint.tenant_id"`)}
	}
	if _, ok := _c.mutation.RecordedAt(); !ok {
		return &ValidationError{Name: "recorded_at", err: errors.New(`ent: missing required field "AuthFileQuotaSnapshotPoint.recorded_at"`)}
	}
	if _, ok := _c.mutation.AuthIndex(); !ok {
		return &ValidationError{Name: "auth_index", err: errors.New(`ent: missing required field "AuthFileQuotaSnapshotPoint.auth_index"`)}
	}
	if _, ok := _c.mutation.AuthSubjectID(); !ok {
		return &ValidationError{Name: "auth_subject_id", err: errors.New(`ent: missing required field "AuthFileQuotaSnapshotPoint.auth_subject_id"`)}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "AuthFileQuotaSnapshotPoint.provider"`)}
	}
	if _, ok := _c.mutation.QuotaKey(); !ok {
		return &ValidationError{Name: "quota_key", err: errors.New(`ent: missing required field "AuthFileQuotaSnapshotPoint.quota_key"`)}
	}
	if _, ok := _c.mutation.QuotaLabel(); !ok {
		return &ValidationError{Name: "quota_label", err: errors.New(`ent: missing required field "AuthFileQuotaSnapshotPoint.quota_label"`)}
	}
	if _, ok := _c.mutation.WindowSeconds(); !ok {
		return &ValidationError{Name: "window_seconds", err: errors.New(`ent: missing required field "AuthFileQuotaSnapshotPoint.window_seconds"`)}
	}
	return nil
}

func (_c *AuthFileQuotaSnapshotPointCreate) sqlSave(ctx context.Context) (*AuthFileQuotaSnapshotPoint, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuthFileQuotaSnapshotPointCreate) createSpec() (*AuthFileQuotaSnapshotPoint, *sqlgraph.CreateSpec) {
	var (
		_node = &AuthFileQuotaSnapshotPoint{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(authfilequotasnapshotpoint.Table, sqlgraph.NewFieldSpec(authfilequotasnapshotpoint.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(authfilequotasnapshotpoint.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.RecordedAt(); ok {
		_spec.SetField(authfilequotasnapshotpoint.FieldRecordedAt, field.TypeTime, value)
		_node.RecordedAt = value
	}
	if value, ok := _c.mutation.AuthIndex(); ok {
		_spec.SetField(authfilequotasnapshotpoint.FieldAuthIndex, field.TypeString, value)
		_node.AuthIndex = value
	}
	if value, ok := _c.mutation.AuthSubjectID(); ok {
		_spec.SetField(authfilequotasnapshotpoint.FieldAuthSubjectID, field.TypeString, value)
		_node.AuthSubjectID = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(authfilequotasnapshotpoint.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.QuotaKey(); ok {
		_spec.SetField(authfilequotasnapshotpoint.FieldQuotaKey, field.TypeString, value)
		_node.QuotaKey = value
	}
	if value, ok := _c.mutation.QuotaLabel(); ok {
		_spec.SetField(authfilequotasnapshotpoint.FieldQuotaLabel, field.TypeString, value)
		_node.QuotaLabel = value
	}
	if value, ok := _c.mutation.Percent(); ok {
		_spec.SetField(authfilequotasnapshotpoint.FieldPercent, field.TypeFloat64, value)
		_node.Percent = &value
	}
	if value, ok := _c.mutation.ResetAt(); ok {
		_spec.SetField(authfilequotasnapshotpoint.FieldResetAt, field.TypeTime, value)
		_node.ResetAt = &value
	}
	if value, ok := _c.mutation.WindowSeconds(); ok {
		_spec.SetField(authfilequotasnapshotpoint.FieldWindowSeconds, field.TypeInt64, value)
		_node.WindowSeconds = value
	}
	return _node, _spec
}

// AuthFileQuotaSnapshotPointCreateBulk is the builder for creating many AuthFileQuotaSnapshotPoint entities in bulk.
type AuthFileQuotaSnapshotPointCreateBulk struct {
	config
	err      error
	builders []*AuthFileQuotaSnapshotPointCreate
}

// Save creates the AuthFileQuotaSnapshotPoint entities in the database.
func (_c *AuthFileQuotaSnapshotPointCreateBulk) Save(ctx context.Context) ([]*AuthFileQuotaSnapshotPoint, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuthFileQuotaSnapshotPoint, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuthFileQuotaSnapshotPointMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuthFileQuotaSnapshotPointCreateBulk) SaveX(ctx context.Context) []*AuthFileQuotaSnapshotPoint {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthFileQuotaSnapshotPointCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthFileQuotaSnapshotPointCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
