// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/router-for-me/CLIProxyAPI/v6/internal/storage/postgres/ent/authsubjectquotacycle"
)

// AuthSubjectQuotaCycleCreate is the builder for creating a AuthSubjectQuotaCycle entity.
type AuthSubjectQuotaCycleCreate struct {
	config
	mutation *AuthSubjectQuotaCycleMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *AuthSubjectQuotaCycleCreate) SetTenantID(v string) *AuthSubjectQuotaCycleCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *AuthSubjectQuotaCycleCreate) SetNillableTenantID(v *string) *AuthSubjectQuotaCycleCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetSubjectID sets the "subject_id" field.
func (_c *AuthSubjectQuotaCycleCreate) SetSubjectID(v string) *AuthSubjectQuotaCycleCreate {
	_c.mutation.SetSubjectID(v)
	return _c
}

// SetAuthIndex sets the "auth_index" field.
func (_c *AuthSubjectQuotaCycleCreate) SetAuthIndex(v string) *AuthSubjectQuotaCycleCreate {
	_c.mutation.SetAuthIndex(v)
	return _c
}

// SetNillableAuthIndex sets the "auth_index" field if the given value is not nil.
func (_c *AuthSubjectQuotaCycleCreate) SetNillableAuthIndex(v *string) *AuthSubjectQuotaCycleCreate {
	if v != nil {
		_c.SetAuthIndex(*v)
	}
	return _c
}

// SetProvider sets the "provider" field.
func (_c *AuthSubjectQuotaCycleCreate) SetProvider(v string) *AuthSubjectQuotaCycleCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *AuthSubjectQuotaCycleCreate) SetNillableProvider(v *string) *AuthSubjectQuotaCycleCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetQuotaKey sets the "quota_key" field.
func (_c *AuthSubjectQuotaCycleCreate) SetQuotaKey(v string) *AuthSubjectQuotaCycleCreate {
	_c.mutation.SetQuotaKey(v)
	return _c
}

// SetCycleStartAt sets the "cycle_start_at" field.
func (_c *AuthSubjectQuotaCycleCreate) SetCycleStartAt(v time.Time) *AuthSubjectQuotaCycleCreate {
	_c.mutation.SetCycleStartAt(v)
	return _c
}

// SetResetAt sets the "reset_at" field.
func (_c *AuthSubjectQuotaCycleCreate) SetResetAt(v time.Time) *AuthSubjectQuotaCycleCreate {
	_c.mutation.SetResetAt(v)
	return _c
}

// SetWindowSeconds sets the "window_seconds" field.
func (_c *AuthSubjectQuotaCycleCreate) SetWindowSeconds(v int64) *AuthSubjectQuotaCycleCreate {
	_c.mutation.SetWindowSeconds(v)
	return _c
}

// SetNillableWindowSeconds sets the "window_seconds" field if the given value is not nil.
func (_c *AuthSubjectQuotaCycleCreate) SetNillableWindowSeconds(v *int64) *AuthSubjectQuotaCycleCreate {
	if v != nil {
		_c.SetWindowSeconds(*v)
	}
	return _c
}

// SetLastVerifiedAt sets the "last_verified_at" field.
func (_c *AuthSubjectQuotaCycleCreate) SetLastVerifiedAt(v time.Time) *AuthSubjectQuotaCycleCreate {
	_c.mutation.SetLastVerifiedAt(v)
	return _c
}

// Mutation returns the AuthSubjectQuotaCycleMutation object of the builder.
func (_c *AuthSubjectQuotaCycleCreate) Mutation() *AuthSubjectQuotaCycleMutation {
	return _c.mutation
}

// Save creates the AuthSubjectQuotaCycle in the database.
func (_c *AuthSubjectQuotaCycleCreate) Save(ctx context.Context) (*AuthSubjectQuotaCycle, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuthSubjectQuotaCycleCreate) SaveX(ctx context.Context) *AuthSubjectQuotaCycle {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthSubjectQuotaCycleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthSubjectQuotaCycleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuthSubjectQuotaCycleCreate) defaults() {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := authsubjectquotacycle.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.AuthIndex(); !ok {
		v := authsubjectquotacycle.DefaultAuthIndex
		_c.mutation.SetAuthIndex(v)
	}
	if _, ok := _c.mutation.Provider(); !ok {
		v := authsubjectquotacycle.DefaultProvider
		_c.mutation.SetProvider(v)
	}
	if _, ok := _c.mutation.WindowSeconds(); !ok {
		v := authsubjectquotacycle.DefaultWindowSeconds
		_c.mutation.SetWindowSeconds(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuthSubjectQuotaCycleCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "AuthSubjectQuotaCycle.tenant_id"`)}
	}
	if _, ok := _c.mutation.SubjectID(); !ok {
		return &ValidationError{Name: "subject_id", err: errors.New(`ent: missing required field "AuthSubjectQuotaCycle.subject_id"`)}
	}
	if _, ok := _c.mutation.AuthIndex(); !ok {
		return &ValidationError{Name: "auth_index", err: errors.New(`ent: missing required field "AuthSubjectQuotaCycle.auth_index"`)}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "AuthSubjectQuotaCycle.provider"`)}
	}
	if _, ok := _c.mutation.QuotaKey(); !ok {
		return &ValidationError{Name: "quota_key", err: errors.New(`ent: missing required field "AuthSubjectQuotaCycle.quota_key"`)}
	}
	if _, ok := _c.mutation.CycleStartAt(); !ok {
		return &ValidationError{Name: "cycle_start_at", err: errors.New(`ent: missing required field "AuthSubjectQuotaCycle.cycle_start_at"`)}
	}
	if _, ok := _c.mutation.ResetAt(); !ok {
		return &ValidationError{Name: "reset_at", err: errors.New(`ent: missing required field "AuthSubjectQuotaCycle.reset_at"`)}
	}
	if _, ok := _c.mutation.WindowSeconds(); !ok {
		return &ValidationError{Name: "window_seconds", err: errors.New(`ent: missing required field "AuthSubjectQuotaCycle.window_seconds"`)}
	}
	if _, ok := _c.mutation.LastVerifiedAt(); !ok {
		return &ValidationError{Name: "last_verified_at", err: errors.New(`ent: missing required field "AuthSubjectQuotaCycle.last_verified_at"`)}
	}
	return nil
}

func (_c *AuthSubjectQuotaCycleCreate) sqlSave(ctx context.Context) (*AuthSubjectQuotaCycle, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuthSubjectQuotaCycleCreate) createSpec() (*AuthSubjectQuotaCycle, *sqlgraph.CreateSpec) {
	var (
		_node = &AuthSubjectQuotaCycle{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(authsubjectquotacycle.Table, sqlgraph.NewFieldSpec(authsubjectquotacycle.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(authsubjectquotacycle.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.SubjectID(); ok {
		_spec.SetField(authsubjectquotacycle.FieldSubjectID, field.TypeString, value)
		_node.SubjectID = value
	}
	if value, ok := _c.mutation.AuthIndex(); ok {
		_spec.SetField(authsubjectquotacycle.FieldAuthIndex, field.TypeString, value)
		_node.AuthIndex = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(authsubjectquotacycle.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.QuotaKey(); ok {
		_spec.SetField(authsubjectquotacycle.FieldQuotaKey, field.TypeString, value)
		_node.QuotaKey = value
	}
	if value, ok := _c.mutation.CycleStartAt(); ok {
		_spec.SetField(authsubjectquotacycle.FieldCycleStartAt, field.TypeTime, value)
		_node.CycleStartAt = value
	}
	if value, ok := _c.mutation.ResetAt(); ok {
		_spec.SetField(authsubjectquotacycle.FieldResetAt, field.TypeTime, value)
		_node.ResetAt = value
	}
	if value, ok := _c.mutation.WindowSeconds(); ok {
		_spec.SetField(authsubjectquotacycle.FieldWindowSeconds, field.TypeInt64, value)
		_node.WindowSeconds = value
	}
	if value, ok := _c.mutation.LastVerifiedAt(); ok {
		_spec.SetField(authsubjectquotacycle.FieldLastVerifiedAt, field.TypeTime, value)
		_node.LastVerifiedAt = value
	}
	return _node, _spec
}

// AuthSubjectQuotaCycleCreateBulk is the builder for creating many AuthSubjectQuotaCycle entities in bulk.
type AuthSubjectQuotaCycleCreateBulk struct {
	config
	err      error
	builders []*AuthSubjectQuotaCycleCreate
}

// Save creates the AuthSubjectQuotaCycle entities in the database.
func (_c *AuthSubjectQuotaCycleCreateBulk) Save(ctx context.Context) ([]*AuthSubjectQuotaCycle, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuthSubjectQuotaCycle, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuthSubjectQuotaCycleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuthSubjectQuotaCycleCreateBulk) SaveX(ctx context.Context) []*AuthSubjectQuotaCycle {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthSubjectQuotaCycleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthSubjectQuotaCycleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
