// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/router-for-me/CLIProxyAPI/v6/internal/storage/postgres/ent/authgroupmodelownermapping"
	"github.com/router-for-me/CLIProxyAPI/v6/internal/storage/postgres/ent/predicate"
)

// AuthGroupModelOwnerMappingDelete is the builder for deleting a AuthGroupModelOwnerMapping entity.
type AuthGroupModelOwnerMappingDelete struct {
	config
	hooks    []Hook
	mutation *AuthGroupModelOwnerMappingMutation
}

// Where appends a list predicates to the AuthGroupModelOwnerMappingDelete builder.
func (_d *AuthGroupModelOwnerMappingDelete) Where(ps ...predicate.AuthGroupModelOwnerMapping) *AuthGroupModelOwnerMappingDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AuthGroupModelOwnerMappingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AuthGroupModelOwnerMappingDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AuthGroupModelOwnerMappingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(authgroupmodelownermapping.Table, sqlgraph.NewFieldSpec(authgroupmodelownermapping.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AuthGroupModelOwnerMappingDeleteOne is the builder for deleting a single AuthGroupModelOwnerMapping entity.
type AuthGroupModelOwnerMappingDeleteOne struct {
	_d *AuthGroupModelOwnerMappingDelete
}

// Where appends a list predicates to the AuthGroupModelOwnerMappingDelete builder.
func (_d *AuthGroupModelOwnerMappingDeleteOne) Where(ps ...predicate.AuthGroupModelOwnerMapping) *AuthGroupModelOwnerMappingDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AuthGroupModelOwnerMappingDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{authgroupmodelownermapping.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AuthGroupModelOwnerMappingDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
