// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/router-for-me/CLIProxyAPI/v6/internal/storage/postgres/ent/authfilequotasnapshotpoint"
	"github.com/router-for-me/CLIProxyAPI/v6/internal/storage/postgres/ent/predicate"
)

// AuthFileQuotaSnapshotPointUpdate is the builder for updating AuthFileQuotaSnapshotPoint entities.
type AuthFileQuotaSnapshotPointUpdate struct {
	config
	hooks    []Hook
	mutation *AuthFileQuotaSnapshotPointMutation
}

// Where appends a list predicates to the AuthFileQuotaSnapshotPointUpdate builder.
func (_u *AuthFileQuotaSnapshotPointUpdate) Where(ps ...predicate.AuthFileQuotaSnapshotPoint) *AuthFileQuotaSnapshotPointUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *AuthFileQuotaSnapshotPointUpdate) SetTenantID(v string) *AuthFileQuotaSnapshotPointUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *AuthFileQuotaSnapshotPointUpdate) SetNillableTenantID(v *string) *AuthFileQuotaSnapshotPointUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetRecordedAt sets the "recorded_at" field.
func (_u *AuthFileQuotaSnapshotPointUpdate) SetRecordedAt(v time.Time) *AuthFileQuotaSnapshotPointUpdate {
	_u.mutation.SetRecordedAt(v)
	return _u
}

// SetNillableRecordedAt sets the "recorded_at" field if the given value is not nil.
func (_u *AuthFileQuotaSnapshotPointUpdate) SetNillableRecordedAt(v *time.Time) *AuthFileQuotaSnapshotPointUpdate {
	if v != nil {
		_u.SetRecordedAt(*v)
	}
	return _u
}

// SetAuthIndex sets the "auth_index" field.
func (_u *AuthFileQuotaSnapshotPointUpdate) SetAuthIndex(v string) *AuthFileQuotaSnapshotPointUpdate {
	_u.mutation.SetAuthIndex(v)
	return _u
}

// SetNillableAuthIndex sets the "auth_index" field if the given value is not nil.
func (_u *AuthFileQuotaSnapshotPointUpdate) SetNillableAuthIndex(v *string) *AuthFileQuotaSnapshotPointUpdate {
	if v != nil {
		_u.SetAuthIndex(*v)
	}
	return _u
}

// SetAuthSubjectID sets the "auth_subject_id" field.
func (_u *AuthFileQuotaSnapshotPointUpdate) SetAuthSubjectID(v string) *AuthFileQuotaSnapshotPointUpdate {
	_u.mutation.SetAuthSubjectID(v)
	return _u
}

// SetNillableAuthSubjectID sets the "auth_subject_id" field if the given value is not nil.
func (_u *AuthFileQuotaSnapshotPointUpdate) SetNillableAuthSubjectID(v *string) *AuthFileQuotaSnapshotPointUpdate {
	if v != nil {
		_u.SetAuthSubjectID(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *AuthFileQuotaSnapshotPointUpdate) SetProvider(v string) *AuthFileQuotaSnapshotPointUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *AuthFileQuotaSnapshotPointUpdate) SetNillableProvider(v *string) *AuthFileQuotaSnapshotPointUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetQuotaKey sets the "quota_key" field.
func (_u *AuthFileQuotaSnapshotPointUpdate) SetQuotaKey(v string) *AuthFileQuotaSnapshotPointUpdate {
	_u.mutation.SetQuotaKey(v)
	return _u
}

// SetNillableQuotaKey sets the "quota_key" field if the given value is not nil.
func (_u *AuthFileQuotaSnapshotPointUpdate) SetNillableQuotaKey(v *string) *AuthFileQuotaSnapshotPointUpdate {
	if v != nil {
		_u.SetQuotaKey(*v)
	}
	return _u
}

// SetQuotaLabel sets the "quota_label" field.
func (_u *AuthFileQuotaSnapshotPointUpdate) SetQuotaLabel(v string) *AuthFileQuotaSnapshotPointUpdate {
	_u.mutation.SetQuotaLabel(v)
	return _u
}

// SetNillableQuotaLabel sets the "quota_label" field if the given value is not nil.
func (_u *AuthFileQuotaSnapshotPointUpdate) SetNillableQuotaLabel(v *string) *AuthFileQuotaSnapshotPointUpdate {
	if v != nil {
		_u.SetQuotaLabel(*v)
	}
	return _u
}

// SetPercent sets the "percent" field.
func (_u *AuthFileQuotaSnapshotPointUpdate) SetPercent(v float64) *AuthFileQuotaSnapshotPointUpdate {
	_u.mutation.ResetPercent()
	_u.mutation.SetPercent(v)
	return _u
}

// SetNillablePercent sets the "percent" field if the given value is not nil.
func (_u *AuthFileQuotaSnapshotPointUpdate) SetNillablePercent(v *float64) *AuthFileQuotaSnapshotPointUpdate {
	if v != nil {
		_u.SetPercent(*v)
	}
	return _u
}

// AddPercent adds value to the "percent" field.
func (_u *AuthFileQuotaSnapshotPointUpdate) AddPercent(v float64) *AuthFileQuotaSnapshotPointUpdate {
	_u.mutation.AddPercent(v)
	return _u
}

// ClearPercent clears the value of the "percent" field.
func (_u *AuthFileQuotaSnapshotPointUpdate) ClearPercent() *AuthFileQuotaSnapshotPointUpdate {
	_u.mutation.ClearPercent()
	return _u
}

// SetResetAt sets the "reset_at" field.
func (_u *AuthFileQuotaSnapshotPointUpdate) SetResetAt(v time.Time) *AuthFileQuotaSnapshotPointUpdate {
	_u.mutation.SetResetAt(v)
	return _u
}

// SetNillableResetAt sets the "reset_at" field if the given value is not nil.
func (_u *AuthFileQuotaSnapshotPointUpdate) SetNillableResetAt(v *time.Time) *AuthFileQuotaSnapshotPointUpdate {
	if v != nil {
		_u.SetResetAt(*v)
	}
	return _u
}

// ClearResetAt clears the value of the "reset_at" field.
func (_u *AuthFileQuotaSnapshotPointUpdate) ClearResetAt() *AuthFileQuotaSnapshotPointUpdate {
	_u.mutation.ClearResetAt()
	return _u
}

// SetWindowSeconds sets the "window_seconds" field.
func (_u *AuthFileQuotaSnapshotPointUpdate) SetWindowSeconds(v int64) *AuthFileQuotaSnapshotPointUpdate {
	_u.mutation.ResetWindowSeconds()
	_u.mutation.SetWindowSeconds(v)
	return _u
}

// SetNillableWindowSeconds sets the "window_seconds" field if the given value is not nil.
func (_u *AuthFileQuotaSnapshotPointUpdate) SetNillableWindowSeconds(v *int64) *AuthFileQuotaSnapshotPointUpdate {
	if v != nil {
		_u.SetWindowSeconds(*v)
	}
	return _u
}

// AddWindowSeconds adds value to the "window_seconds" field.
func (_u *AuthFileQuotaSnapshotPointUpdate) AddWindowSeconds(v int64) *AuthFileQuotaSnapshotPointUpdate {
	_u.mutation.AddWindowSeconds(v)
	return _u
}

// Mutation returns the AuthFileQuotaSnapshotPointMutation object of the builder.
func (_u *AuthFileQuotaSnapshotPointUpdate) Mutation() *AuthFileQuotaSnapshotPointMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuthFileQuotaSnapshotPointUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthFileQuotaSnapshotPointUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuthFileQuotaSnapshotPointUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthFileQuotaSnapshotPointUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AuthFileQuotaSnapshotPointUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(authfilequotasnapshotpoint.Table, authfilequotasnapshotpoint.Columns, sqlgraph.NewFieldSpec(authfilequotasnapshotpoint.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(authfilequotasnapshotpoint.FieldTenantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RecordedAt(); ok {
		_spec.SetField(authfilequotasnapshotpoint.FieldRecordedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AuthIndex(); ok {
		_spec.SetField(authfilequotasnapshotpoint.FieldAuthIndex, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthSubjectID(); ok {
		_spec.SetField(authfilequotasnapshotpoint.FieldAuthSubjectID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(authfilequotasnapshotpoint.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.QuotaKey(); ok {
		_spec.SetField(authfilequotasnapshotpoint.FieldQuotaKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.QuotaLabel(); ok {
		_spec.SetField(authfilequotasnapshotpoint.FieldQuotaLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Percent(); ok {
		_spec.SetField(authfilequotasnapshotpoint.FieldPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPercent(); ok {
		_spec.AddField(authfilequotasnapshotpoint.FieldPercent, field.TypeFloat64, value)
	}
	if _u.mutation.PercentCleared() {
		_spec.ClearField(authfilequotasnapshotpoint.FieldPercent, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ResetAt(); ok {
		_spec.SetField(authfilequotasnapshotpoint.FieldResetAt, field.TypeTime, value)
	}
	if _u.mutation.ResetAtCleared() {
		_spec.ClearField(authfilequotasnapshotpoint.FieldResetAt, field.TypeTime)
	}
	if value, ok := _u.mutation.WindowSeconds(); ok {
		_spec.SetField(authfilequotasnapshotpoint.FieldWindowSeconds, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedWindowSeconds(); ok {
		_spec.AddField(authfilequotasnapshotpoint.FieldWindowSeconds, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authfilequotasnapshotpoint.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuthFileQuotaSnapshotPointUpdateOne is the builder for updating a single AuthFileQuotaSnapshotPoint entity.
type AuthFileQuotaSnapshotPointUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuthFileQuotaSnapshotPointMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *AuthFileQuotaSnapshotPointUpdateOne) SetTenantID(v string) *AuthFileQuotaSnapshotPointUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *AuthFileQuotaSnapshotPointUpdateOne) SetNillableTenantID(v *string) *AuthFileQuotaSnapshotPointUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetRecordedAt sets the "recorded_at" field.
func (_u *AuthFileQuotaSnapshotPointUpdateOne) SetRecordedAt(v time.Time) *AuthFileQuotaSnapshotPointUpdateOne {
	_u.mutation.SetRecordedAt(v)
	return _u
}

// SetNillableRecordedAt sets the "recorded_at" field if the given value is not nil.
func (_u *AuthFileQuotaSnapshotPointUpdateOne) SetNillableRecordedAt(v *time.Time) *AuthFileQuotaSnapshotPointUpdateOne {
	if v != nil {
		_u.SetRecordedAt(*v)
	}
	return _u
}

// SetAuthIndex sets the "auth_index" field.
func (_u *AuthFileQuotaSnapshotPointUpdateOne) SetAuthIndex(v string) *AuthFileQuotaSnapshotPointUpdateOne {
	_u.mutation.SetAuthIndex(v)
	return _u
}

// SetNillableAuthIndex sets the "auth_index" field if the given value is not nil.
func (_u *AuthFileQuotaSnapshotPointUpdateOne) SetNillableAuthIndex(v *string) *AuthFileQuotaSnapshotPointUpdateOne {
	if v != nil {
		_u.SetAuthIndex(*v)
	}
	return _u
}

// SetAuthSubjectID sets the "auth_subject_id" field.
func (_u *AuthFileQuotaSnapshotPointUpdateOne) SetAuthSubjectID(v string) *AuthFileQuotaSnapshotPointUpdateOne {
	_u.mutation.SetAuthSubjectID(v)
	return _u
}

// SetNillableAuthSubjectID sets the "auth_subject_id" field if the given value is not nil.
func (_u *AuthFileQuotaSnapshotPointUpdateOne) SetNillableAuthSubjectID(v *string) *AuthFileQuotaSnapshotPointUpdateOne {
	if v != nil {
		_u.SetAuthSubjectID(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *AuthFileQuotaSnapshotPointUpdateOne) SetProvider(v string) *AuthFileQuotaSnapshotPointUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *AuthFileQuotaSnapshotPointUpdateOne) SetNillableProvider(v *string) *AuthFileQuotaSnapshotPointUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetQuotaKey sets the "quota_key" field.
func (_u *AuthFileQuotaSnapshotPointUpdateOne) SetQuotaKey(v string) *AuthFileQuotaSnapshotPointUpdateOne {
	_u.mutation.SetQuotaKey(v)
	return _u
}

// SetNillableQuotaKey sets the "quota_key" field if the given value is not nil.
func (_u *AuthFileQuotaSnapshotPointUpdateOne) SetNillableQuotaKey(v *string) *AuthFileQuotaSnapshotPointUpdateOne {
	if v != nil {
		_u.SetQuotaKey(*v)
	}
	return _u
}

// SetQuotaLabel sets the "quota_label" field.
func (_u *AuthFileQuotaSnapshotPointUpdateOne) SetQuotaLabel(v string) *AuthFileQuotaSnapshotPointUpdateOne {
	_u.mutation.SetQuotaLabel(v)
	return _u
}

// SetNillableQuotaLabel sets the "quota_label" field if the given value is not nil.
func (_u *AuthFileQuotaSnapshotPointUpdateOne) SetNillableQuotaLabel(v *string) *AuthFileQuotaSnapshotPointUpdateOne {
	if v != nil {
		_u.SetQuotaLabel(*v)
	}
	return _u
}

// SetPercent sets the "percent" field.
func (_u *AuthFileQuotaSnapshotPointUpdateOne) SetPercent(v float64) *AuthFileQuotaSnapshotPointUpdateOne {
	_u.mutation.ResetPercent()
	_u.mutation.SetPercent(v)
	return _u
}

// SetNillablePercent sets the "percent" field if the given value is not nil.
func (_u *AuthFileQuotaSnapshotPointUpdateOne) SetNillablePercent(v *float64) *AuthFileQuotaSnapshotPointUpdateOne {
	if v != nil {
		_u.SetPercent(*v)
	}
	return _u
}

// AddPercent adds value to the "percent" field.
func (_u *AuthFileQuotaSnapshotPointUpdateOne) AddPercent(v float64) *AuthFileQuotaSnapshotPointUpdateOne {
	_u.mutation.AddPercent(v)
	return _u
}

// ClearPercent clears the value of the "percent" field.
func (_u *AuthFileQuotaSnapshotPointUpdateOne) ClearPercent() *AuthFileQuotaSnapshotPointUpdateOne {
	_u.mutation.ClearPercent()
	return _u
}

// SetResetAt sets the "reset_at" field.
func (_u *AuthFileQuotaSnapshotPointUpdateOne) SetResetAt(v time.Time) *AuthFileQuotaSnapshotPointUpdateOne {
	_u.mutation.SetResetAt(v)
	return _u
}

// SetNillableResetAt sets the "reset_at" field if the given value is not nil.
func (_u *AuthFileQuotaSnapshotPointUpdateOne) SetNillableResetAt(v *time.Time) *AuthFileQuotaSnapshotPointUpdateOne {
	if v != nil {
		_u.SetResetAt(*v)
	}
	return _u
}

// ClearResetAt clears the value of the "reset_at" field.
func (_u *AuthFileQuotaSnapshotPointUpdateOne) ClearResetAt() *AuthFileQuotaSnapshotPointUpdateOne {
	_u.mutation.ClearResetAt()
	return _u
}

// SetWindowSeconds sets the "window_seconds" field.
func (_u *AuthFileQuotaSnapshotPointUpdateOne) SetWindowSeconds(v int64) *AuthFileQuotaSnapshotPointUpdateOne {
	_u.mutation.ResetWindowSeconds()
	_u.mutation.SetWindowSeconds(v)
	return _u
}

// SetNillableWindowSeconds sets the "window_seconds" field if the given value is not nil.
func (_u *AuthFileQuotaSnapshotPointUpdateOne) SetNillableWindowSeconds(v *int64) *AuthFileQuotaSnapshotPointUpdateOne {
	if v != nil {
		_u.SetWindowSeconds(*v)
	}
	return _u
}

// AddWindowSeconds adds value to the "window_seconds" field.
func (_u *AuthFileQuotaSnapshotPointUpdateOne) AddWindowSeconds(v int64) *AuthFileQuotaSnapshotPointUpdateOne {
	_u.mutation.AddWindowSeconds(v)
	return _u
}

// Mutation returns the AuthFileQuotaSnapshotPointMutation object of the builder.
func (_u *AuthFileQuotaSnapshotPointUpdateOne) Mutation() *AuthFileQuotaSnapshotPointMutation {
	return _u.mutation
}

// Where appends a list predicates to the AuthFileQuotaSnapshotPointUpdate builder.
func (_u *AuthFileQuotaSnapshotPointUpdateOne) Where(ps ...predicate.AuthFileQuotaSnapshotPoint) *AuthFileQuotaSnapshotPointUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuthFileQuotaSnapshotPointUpdateOne) Select(field string, fields ...string) *AuthFileQuotaSnapshotPointUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuthFileQuotaSnapshotPoint entity.
func (_u *AuthFileQuotaSnapshotPointUpdateOne) Save(ctx context.Context) (*AuthFileQuotaSnapshotPoint, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthFileQuotaSnapshotPointUpdateOne) SaveX(ctx context.Context) *AuthFileQuotaSnapshotPoint {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuthFileQuotaSnapshotPointUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthFileQuotaSnapshotPointUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AuthFileQuotaSnapshotPointUpdateOne) sqlSave(ctx context.Context) (_node *AuthFileQuotaSnapshotPoint, err error) {
	_spec := sqlgraph.NewUpdateSpec(authfilequotasnapshotpoint.Table, authfilequotasnapshotpoint.Columns, sqlgraph.NewFieldSpec(authfilequotasnapshotpoint.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuthFileQuotaSnapshotPoint.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, authfilequotasnapshotpoint.FieldID)
		for _, f := range fields {
			if !authfilequotasnapshotpoint.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != authfilequotasnapshotpoint.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(authfilequotasnapshotpoint.FieldTenantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RecordedAt(); ok {
		_spec.SetField(authfilequotasnapshotpoint.FieldRecordedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AuthIndex(); ok {
		_spec.SetField(authfilequotasnapshotpoint.FieldAuthIndex, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthSubjectID(); ok {
		_spec.SetField(authfilequotasnapshotpoint.FieldAuthSubjectID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(authfilequotasnapshotpoint.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.QuotaKey(); ok {
		_spec.SetField(authfilequotasnapshotpoint.FieldQuotaKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.QuotaLabel(); ok {
		_spec.SetField(authfilequotasnapshotpoint.FieldQuotaLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Percent(); ok {
		_spec.SetField(authfilequotasnapshotpoint.FieldPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPercent(); ok {
		_spec.AddField(authfilequotasnapshotpoint.FieldPercent, field.TypeFloat64, value)
	}
	if _u.mutation.PercentCleared() {
		_spec.ClearField(authfilequotasnapshotpoint.FieldPercent, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ResetAt(); ok {
		_spec.SetField(authfilequotasnapshotpoint.FieldResetAt, field.TypeTime, value)
	}
	if _u.mutation.ResetAtCleared() {
		_spec.ClearField(authfilequotasnapshotpoint.FieldResetAt, field.TypeTime)
	}
	if value, ok := _u.mutation.WindowSeconds(); ok {
		_spec.SetField(authfilequotasnapshotpoint.FieldWindowSeconds, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedWindowSeconds(); ok {
		_spec.AddField(authfilequotasnapshotpoint.FieldWindowSeconds, field.TypeInt64, value)
	}
	_node = &AuthFileQuotaSnapshotPoint{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authfilequotasnapshotpoint.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
