// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/router-for-me/CLIProxyAPI/v6/internal/storage/postgres/ent/ccswitchimportconfig"
)

// CcSwitchImportConfig is the model entity for the CcSwitchImportConfig schema.
type CcSwitchImportConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID string `json:"tenant_id,omitempty"`
	// ClientType holds the value of the "client_type" field.
	ClientType string `json:"client_type,omitempty"`
	// ProviderName holds the value of the "provider_name" field.
	ProviderName string `json:"provider_name,omitempty"`
	// Note holds the value of the "note" field.
	Note string `json:"note,omitempty"`
	// DefaultModel holds the value of the "default_model" field.
	DefaultModel string `json:"default_model,omitempty"`
	// ModelMappings holds the value of the "model_mappings" field.
	ModelMappings string `json:"model_mappings,omitempty"`
	// AllowedChannelGroups holds the value of the "allowed_channel_groups" field.
	AllowedChannelGroups string `json:"allowed_channel_groups,omitempty"`
	// RoutePath holds the value of the "route_path" field.
	RoutePath string `json:"route_path,omitempty"`
	// EndpointPath holds the value of the "endpoint_path" field.
	EndpointPath string `json:"endpoint_path,omitempty"`
	// UsageAutoInterval holds the value of the "usage_auto_interval" field.
	UsageAutoInterval int `json:"usage_auto_interval,omitempty"`
	// APIKeyField holds the value of the "api_key_field" field.
	APIKeyField string `json:"api_key_field,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt string `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    string `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CcSwitchImportConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ccswitchimportconfig.FieldUsageAutoInterval:
			values[i] = new(sql.NullInt64)
		case ccswitchimportconfig.FieldID, ccswitchimportconfig.FieldTenantID, ccswitchimportconfig.FieldClientType, ccswitchimportconfig.FieldProviderName, ccswitchimportconfig.FieldNote, ccswitchimportconfig.FieldDefaultModel, ccswitchimportconfig.FieldModelMappings, ccswitchimportconfig.FieldAllowedChannelGroups, ccswitchimportconfig.FieldRoutePath, ccswitchimportconfig.FieldEndpointPath, ccswitchimportconfig.FieldAPIKeyField, ccswitchimportconfig.FieldCreatedAt, ccswitchimportconfig.FieldUpdatedAt:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CcSwitchImportConfig fields.
func (_m *CcSwitchImportConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ccswitchimportconfig.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case ccswitchimportconfig.FieldTenantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = value.String
			}
		case ccswitchimportconfig.FieldClientType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_type", values[i])
			} else if value.Valid {
				_m.ClientType = value.String
			}
		case ccswitchimportconfig.FieldProviderName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_name", values[i])
			} else if value.Valid {
				_m.ProviderName = value.String
			}
		case ccswitchimportconfig.FieldNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field note", values[i])
			} else if value.Valid {
				_m.Note = value.String
			}
		case ccswitchimportconfig.FieldDefaultModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field default_model", values[i])
			} else if value.Valid {
				_m.DefaultModel = value.String
			}
		case ccswitchimportconfig.FieldModelMappings:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_mappings", values[i])
			} else if value.Valid {
				_m.ModelMappings = value.String
			}
		case ccswitchimportconfig.FieldAllowedChannelGroups:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field allowed_channel_groups", values[i])
			} else if value.Valid {
				_m.AllowedChannelGroups = value.String
			}
		case ccswitchimportconfig.FieldRoutePath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field route_path", values[i])
			} else if value.Valid {
				_m.RoutePath = value.String
			}
		case ccswitchimportconfig.FieldEndpointPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field endpoint_path", values[i])
			} else if value.Valid {
				_m.EndpointPath = value.String
			}
		case ccswitchimportconfig.FieldUsageAutoInterval:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field usage_auto_interval", values[i])
			} else if value.Valid {
				_m.UsageAutoInterval = int(value.Int64)
			}
		case ccswitchimportconfig.FieldAPIKeyField:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_field", values[i])
			} else if value.Valid {
				_m.APIKeyField = value.String
			}
		case ccswitchimportconfig.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.String
			}
		case ccswitchimportconfig.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CcSwitchImportConfig.
// This includes values selected through modifiers, order, etc.
func (_m *CcSwitchImportConfig) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CcSwitchImportConfig.
// Note that you need to call CcSwitchImportConfig.Unwrap() before calling this method if this CcSwitchImportConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CcSwitchImportConfig) Update() *CcSwitchImportConfigUpdateOne {
	return NewCcSwitchImportConfigClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CcSwitchImportConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CcSwitchImportConfig) Unwrap() *CcSwitchImportConfig {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CcSwitchImportConfig is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CcSwitchImportConfig) String() string {
	var builder strings.Builder
	builder.WriteString("CcSwitchImportConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(_m.TenantID)
	builder.WriteString(", ")
	builder.WriteString("client_type=")
	builder.WriteString(_m.ClientType)
	builder.WriteString(", ")
	builder.WriteString("provider_name=")
	builder.WriteString(_m.ProviderName)
	builder.WriteString(", ")
	builder.WriteString("note=")
	builder.WriteString(_m.Note)
	builder.WriteString(", ")
	builder.WriteString("default_model=")
	builder.WriteString(_m.DefaultModel)
	builder.WriteString(", ")
	builder.WriteString("model_mappings=")
	builder.WriteString(_m.ModelMappings)
	builder.WriteString(", ")
	builder.WriteString("allowed_channel_groups=")
	builder.WriteString(_m.AllowedChannelGroups)
	builder.WriteString(", ")
	builder.WriteString("route_path=")
	builder.WriteString(_m.RoutePath)
	builder.WriteString(", ")
	builder.WriteString("endpoint_path=")
	builder.WriteString(_m.EndpointPath)
	builder.WriteString(", ")
	builder.WriteString("usage_auto_interval=")
	builder.WriteString(fmt.Sprintf("%v", _m.UsageAutoInterval))
	builder.WriteString(", ")
	builder.WriteString("api_key_field=")
	builder.WriteString(_m.APIKeyField)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt)
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt)
	builder.WriteByte(')')
	return builder.String()
}

// CcSwitchImportConfigs is a parsable slice of CcSwitchImportConfig.
type CcSwitchImportConfigs []*CcSwitchImportConfig
