// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/router-for-me/CLIProxyAPI/v6/internal/storage/postgres/ent/identityfingerprintaccountpolicy"
)

// IdentityFingerprintAccountPolicyCreate is the builder for creating a IdentityFingerprintAccountPolicy entity.
type IdentityFingerprintAccountPolicyCreate struct {
	config
	mutation *IdentityFingerprintAccountPolicyMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *IdentityFingerprintAccountPolicyCreate) SetTenantID(v string) *IdentityFingerprintAccountPolicyCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *IdentityFingerprintAccountPolicyCreate) SetNillableTenantID(v *string) *IdentityFingerprintAccountPolicyCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetProvider sets the "provider" field.
func (_c *IdentityFingerprintAccountPolicyCreate) SetProvider(v string) *IdentityFingerprintAccountPolicyCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetAccountKey sets the "account_key" field.
func (_c *IdentityFingerprintAccountPolicyCreate) SetAccountKey(v string) *IdentityFingerprintAccountPolicyCreate {
	_c.mutation.SetAccountKey(v)
	return _c
}

// SetStrategy sets the "strategy" field.
func (_c *IdentityFingerprintAccountPolicyCreate) SetStrategy(v string) *IdentityFingerprintAccountPolicyCreate {
	_c.mutation.SetStrategy(v)
	return _c
}

// SetNillableStrategy sets the "strategy" field if the given value is not nil.
func (_c *IdentityFingerprintAccountPolicyCreate) SetNillableStrategy(v *string) *IdentityFingerprintAccountPolicyCreate {
	if v != nil {
		_c.SetStrategy(*v)
	}
	return _c
}

// SetActiveProfileKey sets the "active_profile_key" field.
func (_c *IdentityFingerprintAccountPolicyCreate) SetActiveProfileKey(v string) *IdentityFingerprintAccountPolicyCreate {
	_c.mutation.SetActiveProfileKey(v)
	return _c
}

// SetNillableActiveProfileKey sets the "active_profile_key" field if the given value is not nil.
func (_c *IdentityFingerprintAccountPolicyCreate) SetNillableActiveProfileKey(v *string) *IdentityFingerprintAccountPolicyCreate {
	if v != nil {
		_c.SetActiveProfileKey(*v)
	}
	return _c
}

// SetRevision sets the "revision" field.
func (_c *IdentityFingerprintAccountPolicyCreate) SetRevision(v int64) *IdentityFingerprintAccountPolicyCreate {
	_c.mutation.SetRevision(v)
	return _c
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_c *IdentityFingerprintAccountPolicyCreate) SetNillableRevision(v *int64) *IdentityFingerprintAccountPolicyCreate {
	if v != nil {
		_c.SetRevision(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *IdentityFingerprintAccountPolicyCreate) SetUpdatedAt(v string) *IdentityFingerprintAccountPolicyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *IdentityFingerprintAccountPolicyCreate) SetNillableUpdatedAt(v *string) *IdentityFingerprintAccountPolicyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the IdentityFingerprintAccountPolicyMutation object of the builder.
func (_c *IdentityFingerprintAccountPolicyCreate) Mutation() *IdentityFingerprintAccountPolicyMutation {
	return _c.mutation
}

// Save creates the IdentityFingerprintAccountPolicy in the database.
func (_c *IdentityFingerprintAccountPolicyCreate) Save(ctx context.Context) (*IdentityFingerprintAccountPolicy, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *IdentityFingerprintAccountPolicyCreate) SaveX(ctx context.Context) *IdentityFingerprintAccountPolicy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IdentityFingerprintAccountPolicyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IdentityFingerprintAccountPolicyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *IdentityFingerprintAccountPolicyCreate) defaults() {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := identityfingerprintaccountpolicy.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.Strategy(); !ok {
		v := identityfingerprintaccountpolicy.DefaultStrategy
		_c.mutation.SetStrategy(v)
	}
	if _, ok := _c.mutation.ActiveProfileKey(); !ok {
		v := identityfingerprintaccountpolicy.DefaultActiveProfileKey
		_c.mutation.SetActiveProfileKey(v)
	}
	if _, ok := _c.mutation.Revision(); !ok {
		v := identityfingerprintaccountpolicy.DefaultRevision
		_c.mutation.SetRevision(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := identityfingerprintaccountpolicy.DefaultUpdatedAt
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *IdentityFingerprintAccountPolicyCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "IdentityFingerprintAccountPolicy.tenant_id"`)}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "IdentityFingerprintAccountPolicy.provider"`)}
	}
	if _, ok := _c.mutation.AccountKey(); !ok {
		return &ValidationError{Name: "account_key", err: errors.New(`ent: missing required field "IdentityFingerprintAccountPolicy.account_key"`)}
	}
	if _, ok := _c.mutation.Strategy(); !ok {
		return &ValidationError{Name: "strategy", err: errors.New(`ent: missing required field "IdentityFingerprintAccountPolicy.strategy"`)}
	}
	if _, ok := _c.mutation.ActiveProfileKey(); !ok {
		return &ValidationError{Name: "active_profile_key", err: errors.New(`ent: missing required field "IdentityFingerprintAccountPolicy.active_profile_key"`)}
	}
	if _, ok := _c.mutation.Revision(); !ok {
		return &ValidationError{Name: "revision", err: errors.New(`ent: missing required field "IdentityFingerprintAccountPolicy.revision"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "IdentityFingerprintAccountPolicy.updated_at"`)}
	}
	return nil
}

func (_c *IdentityFingerprintAccountPolicyCreate) sqlSave(ctx context.Context) (*IdentityFingerprintAccountPolicy, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *IdentityFingerprintAccountPolicyCreate) createSpec() (*IdentityFingerprintAccountPolicy, *sqlgraph.CreateSpec) {
	var (
		_node = &IdentityFingerprintAccountPolicy{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(identityfingerprintaccountpolicy.Table, sqlgraph.NewFieldSpec(identityfingerprintaccountpolicy.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(identityfingerprintaccountpolicy.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(identityfingerprintaccountpolicy.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.AccountKey(); ok {
		_spec.SetField(identityfingerprintaccountpolicy.FieldAccountKey, field.TypeString, value)
		_node.AccountKey = value
	}
	if value, ok := _c.mutation.Strategy(); ok {
		_spec.SetField(identityfingerprintaccountpolicy.FieldStrategy, field.TypeString, value)
		_node.Strategy = value
	}
	if value, ok := _c.mutation.ActiveProfileKey(); ok {
		_spec.SetField(identityfingerprintaccountpolicy.FieldActiveProfileKey, field.TypeString, value)
		_node.ActiveProfileKey = value
	}
	if value, ok := _c.mutation.Revision(); ok {
		_spec.SetField(identityfingerprintaccountpolicy.FieldRevision, field.TypeInt64, value)
		_node.Revision = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(identityfingerprintaccountpolicy.FieldUpdatedAt, field.TypeString, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// IdentityFingerprintAccountPolicyCreateBulk is the builder for creating many IdentityFingerprintAccountPolicy entities in bulk.
type IdentityFingerprintAccountPolicyCreateBulk struct {
	config
	err      error
	builders []*IdentityFingerprintAccountPolicyCreate
}

// Save creates the IdentityFingerprintAccountPolicy entities in the database.
func (_c *IdentityFingerprintAccountPolicyCreateBulk) Save(ctx context.Context) ([]*IdentityFingerprintAccountPolicy, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*IdentityFingerprintAccountPolicy, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IdentityFingerprintAccountPolicyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *IdentityFingerprintAccountPolicyCreateBulk) SaveX(ctx context.Context) []*IdentityFingerprintAccountPolicy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IdentityFingerprintAccountPolicyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IdentityFingerprintAccountPolicyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
