// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/router-for-me/CLIProxyAPI/v6/internal/storage/postgres/ent/modelpricing"
	"github.com/router-for-me/CLIProxyAPI/v6/internal/storage/postgres/ent/predicate"
)

// ModelPricingUpdate is the builder for updating ModelPricing entities.
type ModelPricingUpdate struct {
	config
	hooks    []Hook
	mutation *ModelPricingMutation
}

// Where appends a list predicates to the ModelPricingUpdate builder.
func (_u *ModelPricingUpdate) Where(ps ...predicate.ModelPricing) *ModelPricingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *ModelPricingUpdate) SetTenantID(v string) *ModelPricingUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableTenantID(v *string) *ModelPricingUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *ModelPricingUpdate) SetModelID(v string) *ModelPricingUpdate {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableModelID(v *string) *ModelPricingUpdate {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// SetInputPricePerMillion sets the "input_price_per_million" field.
func (_u *ModelPricingUpdate) SetInputPricePerMillion(v float64) *ModelPricingUpdate {
	_u.mutation.ResetInputPricePerMillion()
	_u.mutation.SetInputPricePerMillion(v)
	return _u
}

// SetNillableInputPricePerMillion sets the "input_price_per_million" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableInputPricePerMillion(v *float64) *ModelPricingUpdate {
	if v != nil {
		_u.SetInputPricePerMillion(*v)
	}
	return _u
}

// AddInputPricePerMillion adds value to the "input_price_per_million" field.
func (_u *ModelPricingUpdate) AddInputPricePerMillion(v float64) *ModelPricingUpdate {
	_u.mutation.AddInputPricePerMillion(v)
	return _u
}

// SetOutputPricePerMillion sets the "output_price_per_million" field.
func (_u *ModelPricingUpdate) SetOutputPricePerMillion(v float64) *ModelPricingUpdate {
	_u.mutation.ResetOutputPricePerMillion()
	_u.mutation.SetOutputPricePerMillion(v)
	return _u
}

// SetNillableOutputPricePerMillion sets the "output_price_per_million" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableOutputPricePerMillion(v *float64) *ModelPricingUpdate {
	if v != nil {
		_u.SetOutputPricePerMillion(*v)
	}
	return _u
}

// AddOutputPricePerMillion adds value to the "output_price_per_million" field.
func (_u *ModelPricingUpdate) AddOutputPricePerMillion(v float64) *ModelPricingUpdate {
	_u.mutation.AddOutputPricePerMillion(v)
	return _u
}

// SetCachedPricePerMillion sets the "cached_price_per_million" field.
func (_u *ModelPricingUpdate) SetCachedPricePerMillion(v float64) *ModelPricingUpdate {
	_u.mutation.ResetCachedPricePerMillion()
	_u.mutation.SetCachedPricePerMillion(v)
	return _u
}

// SetNillableCachedPricePerMillion sets the "cached_price_per_million" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableCachedPricePerMillion(v *float64) *ModelPricingUpdate {
	if v != nil {
		_u.SetCachedPricePerMillion(*v)
	}
	return _u
}

// AddCachedPricePerMillion adds value to the "cached_price_per_million" field.
func (_u *ModelPricingUpdate) AddCachedPricePerMillion(v float64) *ModelPricingUpdate {
	_u.mutation.AddCachedPricePerMillion(v)
	return _u
}

// SetCacheReadPricePerMillion sets the "cache_read_price_per_million" field.
func (_u *ModelPricingUpdate) SetCacheReadPricePerMillion(v float64) *ModelPricingUpdate {
	_u.mutation.ResetCacheReadPricePerMillion()
	_u.mutation.SetCacheReadPricePerMillion(v)
	return _u
}

// SetNillableCacheReadPricePerMillion sets the "cache_read_price_per_million" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableCacheReadPricePerMillion(v *float64) *ModelPricingUpdate {
	if v != nil {
		_u.SetCacheReadPricePerMillion(*v)
	}
	return _u
}

// AddCacheReadPricePerMillion adds value to the "cache_read_price_per_million" field.
func (_u *ModelPricingUpdate) AddCacheReadPricePerMillion(v float64) *ModelPricingUpdate {
	_u.mutation.AddCacheReadPricePerMillion(v)
	return _u
}

// SetCacheWritePricePerMillion sets the "cache_write_price_per_million" field.
func (_u *ModelPricingUpdate) SetCacheWritePricePerMillion(v float64) *ModelPricingUpdate {
	_u.mutation.ResetCacheWritePricePerMillion()
	_u.mutation.SetCacheWritePricePerMillion(v)
	return _u
}

// SetNillableCacheWritePricePerMillion sets the "cache_write_price_per_million" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableCacheWritePricePerMillion(v *float64) *ModelPricingUpdate {
	if v != nil {
		_u.SetCacheWritePricePerMillion(*v)
	}
	return _u
}

// AddCacheWritePricePerMillion adds value to the "cache_write_price_per_million" field.
func (_u *ModelPricingUpdate) AddCacheWritePricePerMillion(v float64) *ModelPricingUpdate {
	_u.mutation.AddCacheWritePricePerMillion(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelPricingUpdate) SetUpdatedAt(v time.Time) *ModelPricingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ModelPricingUpdate) SetNillableUpdatedAt(v *time.Time) *ModelPricingUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the ModelPricingMutation object of the builder.
func (_u *ModelPricingUpdate) Mutation() *ModelPricingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ModelPricingUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelPricingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ModelPricingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelPricingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ModelPricingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(modelpricing.Table, modelpricing.Columns, sqlgraph.NewFieldSpec(modelpricing.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(modelpricing.FieldTenantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(modelpricing.FieldModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputPricePerMillion(); ok {
		_spec.SetField(modelpricing.FieldInputPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedInputPricePerMillion(); ok {
		_spec.AddField(modelpricing.FieldInputPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OutputPricePerMillion(); ok {
		_spec.SetField(modelpricing.FieldOutputPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOutputPricePerMillion(); ok {
		_spec.AddField(modelpricing.FieldOutputPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CachedPricePerMillion(); ok {
		_spec.SetField(modelpricing.FieldCachedPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCachedPricePerMillion(); ok {
		_spec.AddField(modelpricing.FieldCachedPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CacheReadPricePerMillion(); ok {
		_spec.SetField(modelpricing.FieldCacheReadPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadPricePerMillion(); ok {
		_spec.AddField(modelpricing.FieldCacheReadPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CacheWritePricePerMillion(); ok {
		_spec.SetField(modelpricing.FieldCacheWritePricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheWritePricePerMillion(); ok {
		_spec.AddField(modelpricing.FieldCacheWritePricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelpricing.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelpricing.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ModelPricingUpdateOne is the builder for updating a single ModelPricing entity.
type ModelPricingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ModelPricingMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *ModelPricingUpdateOne) SetTenantID(v string) *ModelPricingUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableTenantID(v *string) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *ModelPricingUpdateOne) SetModelID(v string) *ModelPricingUpdateOne {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableModelID(v *string) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// SetInputPricePerMillion sets the "input_price_per_million" field.
func (_u *ModelPricingUpdateOne) SetInputPricePerMillion(v float64) *ModelPricingUpdateOne {
	_u.mutation.ResetInputPricePerMillion()
	_u.mutation.SetInputPricePerMillion(v)
	return _u
}

// SetNillableInputPricePerMillion sets the "input_price_per_million" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableInputPricePerMillion(v *float64) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetInputPricePerMillion(*v)
	}
	return _u
}

// AddInputPricePerMillion adds value to the "input_price_per_million" field.
func (_u *ModelPricingUpdateOne) AddInputPricePerMillion(v float64) *ModelPricingUpdateOne {
	_u.mutation.AddInputPricePerMillion(v)
	return _u
}

// SetOutputPricePerMillion sets the "output_price_per_million" field.
func (_u *ModelPricingUpdateOne) SetOutputPricePerMillion(v float64) *ModelPricingUpdateOne {
	_u.mutation.ResetOutputPricePerMillion()
	_u.mutation.SetOutputPricePerMillion(v)
	return _u
}

// SetNillableOutputPricePerMillion sets the "output_price_per_million" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableOutputPricePerMillion(v *float64) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetOutputPricePerMillion(*v)
	}
	return _u
}

// AddOutputPricePerMillion adds value to the "output_price_per_million" field.
func (_u *ModelPricingUpdateOne) AddOutputPricePerMillion(v float64) *ModelPricingUpdateOne {
	_u.mutation.AddOutputPricePerMillion(v)
	return _u
}

// SetCachedPricePerMillion sets the "cached_price_per_million" field.
func (_u *ModelPricingUpdateOne) SetCachedPricePerMillion(v float64) *ModelPricingUpdateOne {
	_u.mutation.ResetCachedPricePerMillion()
	_u.mutation.SetCachedPricePerMillion(v)
	return _u
}

// SetNillableCachedPricePerMillion sets the "cached_price_per_million" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableCachedPricePerMillion(v *float64) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetCachedPricePerMillion(*v)
	}
	return _u
}

// AddCachedPricePerMillion adds value to the "cached_price_per_million" field.
func (_u *ModelPricingUpdateOne) AddCachedPricePerMillion(v float64) *ModelPricingUpdateOne {
	_u.mutation.AddCachedPricePerMillion(v)
	return _u
}

// SetCacheReadPricePerMillion sets the "cache_read_price_per_million" field.
func (_u *ModelPricingUpdateOne) SetCacheReadPricePerMillion(v float64) *ModelPricingUpdateOne {
	_u.mutation.ResetCacheReadPricePerMillion()
	_u.mutation.SetCacheReadPricePerMillion(v)
	return _u
}

// SetNillableCacheReadPricePerMillion sets the "cache_read_price_per_million" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableCacheReadPricePerMillion(v *float64) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetCacheReadPricePerMillion(*v)
	}
	return _u
}

// AddCacheReadPricePerMillion adds value to the "cache_read_price_per_million" field.
func (_u *ModelPricingUpdateOne) AddCacheReadPricePerMillion(v float64) *ModelPricingUpdateOne {
	_u.mutation.AddCacheReadPricePerMillion(v)
	return _u
}

// SetCacheWritePricePerMillion sets the "cache_write_price_per_million" field.
func (_u *ModelPricingUpdateOne) SetCacheWritePricePerMillion(v float64) *ModelPricingUpdateOne {
	_u.mutation.ResetCacheWritePricePerMillion()
	_u.mutation.SetCacheWritePricePerMillion(v)
	return _u
}

// SetNillableCacheWritePricePerMillion sets the "cache_write_price_per_million" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableCacheWritePricePerMillion(v *float64) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetCacheWritePricePerMillion(*v)
	}
	return _u
}

// AddCacheWritePricePerMillion adds value to the "cache_write_price_per_million" field.
func (_u *ModelPricingUpdateOne) AddCacheWritePricePerMillion(v float64) *ModelPricingUpdateOne {
	_u.mutation.AddCacheWritePricePerMillion(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelPricingUpdateOne) SetUpdatedAt(v time.Time) *ModelPricingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ModelPricingUpdateOne) SetNillableUpdatedAt(v *time.Time) *ModelPricingUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the ModelPricingMutation object of the builder.
func (_u *ModelPricingUpdateOne) Mutation() *ModelPricingMutation {
	return _u.mutation
}

// Where appends a list predicates to the ModelPricingUpdate builder.
func (_u *ModelPricingUpdateOne) Where(ps ...predicate.ModelPricing) *ModelPricingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ModelPricingUpdateOne) Select(field string, fields ...string) *ModelPricingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ModelPricing entity.
func (_u *ModelPricingUpdateOne) Save(ctx context.Context) (*ModelPricing, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelPricingUpdateOne) SaveX(ctx context.Context) *ModelPricing {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ModelPricingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelPricingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ModelPricingUpdateOne) sqlSave(ctx context.Context) (_node *ModelPricing, err error) {
	_spec := sqlgraph.NewUpdateSpec(modelpricing.Table, modelpricing.Columns, sqlgraph.NewFieldSpec(modelpricing.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ModelPricing.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, modelpricing.FieldID)
		for _, f := range fields {
			if !modelpricing.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != modelpricing.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(modelpricing.FieldTenantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(modelpricing.FieldModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputPricePerMillion(); ok {
		_spec.SetField(modelpricing.FieldInputPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedInputPricePerMillion(); ok {
		_spec.AddField(modelpricing.FieldInputPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OutputPricePerMillion(); ok {
		_spec.SetField(modelpricing.FieldOutputPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOutputPricePerMillion(); ok {
		_spec.AddField(modelpricing.FieldOutputPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CachedPricePerMillion(); ok {
		_spec.SetField(modelpricing.FieldCachedPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCachedPricePerMillion(); ok {
		_spec.AddField(modelpricing.FieldCachedPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CacheReadPricePerMillion(); ok {
		_spec.SetField(modelpricing.FieldCacheReadPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadPricePerMillion(); ok {
		_spec.AddField(modelpricing.FieldCacheReadPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CacheWritePricePerMillion(); ok {
		_spec.SetField(modelpricing.FieldCacheWritePricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheWritePricePerMillion(); ok {
		_spec.AddField(modelpricing.FieldCacheWritePricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelpricing.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ModelPricing{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelpricing.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
