// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/router-for-me/CLIProxyAPI/v6/internal/storage/postgres/ent/modelconfig"
)

// ModelConfig is the model entity for the ModelConfig schema.
type ModelConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID string `json:"tenant_id,omitempty"`
	// ModelID holds the value of the "model_id" field.
	ModelID string `json:"model_id,omitempty"`
	// OwnedBy holds the value of the "owned_by" field.
	OwnedBy string `json:"owned_by,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled int `json:"enabled,omitempty"`
	// InputModalities holds the value of the "input_modalities" field.
	InputModalities string `json:"input_modalities,omitempty"`
	// OutputModalities holds the value of the "output_modalities" field.
	OutputModalities string `json:"output_modalities,omitempty"`
	// PricingMode holds the value of the "pricing_mode" field.
	PricingMode string `json:"pricing_mode,omitempty"`
	// InputPricePerMillion holds the value of the "input_price_per_million" field.
	InputPricePerMillion float64 `json:"input_price_per_million,omitempty"`
	// OutputPricePerMillion holds the value of the "output_price_per_million" field.
	OutputPricePerMillion float64 `json:"output_price_per_million,omitempty"`
	// CachedPricePerMillion holds the value of the "cached_price_per_million" field.
	CachedPricePerMillion float64 `json:"cached_price_per_million,omitempty"`
	// CacheReadPricePerMillion holds the value of the "cache_read_price_per_million" field.
	CacheReadPricePerMillion float64 `json:"cache_read_price_per_million,omitempty"`
	// CacheWritePricePerMillion holds the value of the "cache_write_price_per_million" field.
	CacheWritePricePerMillion float64 `json:"cache_write_price_per_million,omitempty"`
	// PricePerCall holds the value of the "price_per_call" field.
	PricePerCall float64 `json:"price_per_call,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ModelConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case modelconfig.FieldInputPricePerMillion, modelconfig.FieldOutputPricePerMillion, modelconfig.FieldCachedPricePerMillion, modelconfig.FieldCacheReadPricePerMillion, modelconfig.FieldCacheWritePricePerMillion, modelconfig.FieldPricePerCall:
			values[i] = new(sql.NullFloat64)
		case modelconfig.FieldID, modelconfig.FieldEnabled:
			values[i] = new(sql.NullInt64)
		case modelconfig.FieldTenantID, modelconfig.FieldModelID, modelconfig.FieldOwnedBy, modelconfig.FieldDescription, modelconfig.FieldInputModalities, modelconfig.FieldOutputModalities, modelconfig.FieldPricingMode, modelconfig.FieldSource:
			values[i] = new(sql.NullString)
		case modelconfig.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ModelConfig fields.
func (_m *ModelConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case modelconfig.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case modelconfig.FieldTenantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = value.String
			}
		case modelconfig.FieldModelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_id", values[i])
			} else if value.Valid {
				_m.ModelID = value.String
			}
		case modelconfig.FieldOwnedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field owned_by", values[i])
			} else if value.Valid {
				_m.OwnedBy = value.String
			}
		case modelconfig.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case modelconfig.FieldEnabled:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = int(value.Int64)
			}
		case modelconfig.FieldInputModalities:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field input_modalities", values[i])
			} else if value.Valid {
				_m.InputModalities = value.String
			}
		case modelconfig.FieldOutputModalities:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field output_modalities", values[i])
			} else if value.Valid {
				_m.OutputModalities = value.String
			}
		case modelconfig.FieldPricingMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pricing_mode", values[i])
			} else if value.Valid {
				_m.PricingMode = value.String
			}
		case modelconfig.FieldInputPricePerMillion:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field input_price_per_million", values[i])
			} else if value.Valid {
				_m.InputPricePerMillion = value.Float64
			}
		case modelconfig.FieldOutputPricePerMillion:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field output_price_per_million", values[i])
			} else if value.Valid {
				_m.OutputPricePerMillion = value.Float64
			}
		case modelconfig.FieldCachedPricePerMillion:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cached_price_per_million", values[i])
			} else if value.Valid {
				_m.CachedPricePerMillion = value.Float64
			}
		case modelconfig.FieldCacheReadPricePerMillion:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_read_price_per_million", values[i])
			} else if value.Valid {
				_m.CacheReadPricePerMillion = value.Float64
			}
		case modelconfig.FieldCacheWritePricePerMillion:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_write_price_per_million", values[i])
			} else if value.Valid {
				_m.CacheWritePricePerMillion = value.Float64
			}
		case modelconfig.FieldPricePerCall:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field price_per_call", values[i])
			} else if value.Valid {
				_m.PricePerCall = value.Float64
			}
		case modelconfig.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case modelconfig.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ModelConfig.
// This includes values selected through modifiers, order, etc.
func (_m *ModelConfig) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ModelConfig.
// Note that you need to call ModelConfig.Unwrap() before calling this method if this ModelConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ModelConfig) Update() *ModelConfigUpdateOne {
	return NewModelConfigClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ModelConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ModelConfig) Unwrap() *ModelConfig {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ModelConfig is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ModelConfig) String() string {
	var builder strings.Builder
	builder.WriteString("ModelConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(_m.TenantID)
	builder.WriteString(", ")
	builder.WriteString("model_id=")
	builder.WriteString(_m.ModelID)
	builder.WriteString(", ")
	builder.WriteString("owned_by=")
	builder.WriteString(_m.OwnedBy)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("input_modalities=")
	builder.WriteString(_m.InputModalities)
	builder.WriteString(", ")
	builder.WriteString("output_modalities=")
	builder.WriteString(_m.OutputModalities)
	builder.WriteString(", ")
	builder.WriteString("pricing_mode=")
	builder.WriteString(_m.PricingMode)
	builder.WriteString(", ")
	builder.WriteString("input_price_per_million=")
	builder.WriteString(fmt.Sprintf("%v", _m.InputPricePerMillion))
	builder.WriteString(", ")
	builder.WriteString("output_price_per_million=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutputPricePerMillion))
	builder.WriteString(", ")
	builder.WriteString("cached_price_per_million=")
	builder.WriteString(fmt.Sprintf("%v", _m.CachedPricePerMillion))
	builder.WriteString(", ")
	builder.WriteString("cache_read_price_per_million=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheReadPricePerMillion))
	builder.WriteString(", ")
	builder.WriteString("cache_write_price_per_million=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheWritePricePerMillion))
	builder.WriteString(", ")
	builder.WriteString("price_per_call=")
	builder.WriteString(fmt.Sprintf("%v", _m.PricePerCall))
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ModelConfigs is a parsable slice of ModelConfig.
type ModelConfigs []*ModelConfig
