// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/router-for-me/CLIProxyAPI/v6/internal/storage/postgres/ent/modelconfig"
	"github.com/router-for-me/CLIProxyAPI/v6/internal/storage/postgres/ent/predicate"
)

// ModelConfigUpdate is the builder for updating ModelConfig entities.
type ModelConfigUpdate struct {
	config
	hooks    []Hook
	mutation *ModelConfigMutation
}

// Where appends a list predicates to the ModelConfigUpdate builder.
func (_u *ModelConfigUpdate) Where(ps ...predicate.ModelConfig) *ModelConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *ModelConfigUpdate) SetTenantID(v string) *ModelConfigUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *ModelConfigUpdate) SetNillableTenantID(v *string) *ModelConfigUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *ModelConfigUpdate) SetModelID(v string) *ModelConfigUpdate {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *ModelConfigUpdate) SetNillableModelID(v *string) *ModelConfigUpdate {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// SetOwnedBy sets the "owned_by" field.
func (_u *ModelConfigUpdate) SetOwnedBy(v string) *ModelConfigUpdate {
	_u.mutation.SetOwnedBy(v)
	return _u
}

// SetNillableOwnedBy sets the "owned_by" field if the given value is not nil.
func (_u *ModelConfigUpdate) SetNillableOwnedBy(v *string) *ModelConfigUpdate {
	if v != nil {
		_u.SetOwnedBy(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ModelConfigUpdate) SetDescription(v string) *ModelConfigUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ModelConfigUpdate) SetNillableDescription(v *string) *ModelConfigUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ModelConfigUpdate) SetEnabled(v int) *ModelConfigUpdate {
	_u.mutation.ResetEnabled()
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ModelConfigUpdate) SetNillableEnabled(v *int) *ModelConfigUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// AddEnabled adds value to the "enabled" field.
func (_u *ModelConfigUpdate) AddEnabled(v int) *ModelConfigUpdate {
	_u.mutation.AddEnabled(v)
	return _u
}

// SetInputModalities sets the "input_modalities" field.
func (_u *ModelConfigUpdate) SetInputModalities(v string) *ModelConfigUpdate {
	_u.mutation.SetInputModalities(v)
	return _u
}

// SetNillableInputModalities sets the "input_modalities" field if the given value is not nil.
func (_u *ModelConfigUpdate) SetNillableInputModalities(v *string) *ModelConfigUpdate {
	if v != nil {
		_u.SetInputModalities(*v)
	}
	return _u
}

// SetOutputModalities sets the "output_modalities" field.
func (_u *ModelConfigUpdate) SetOutputModalities(v string) *ModelConfigUpdate {
	_u.mutation.SetOutputModalities(v)
	return _u
}

// SetNillableOutputModalities sets the "output_modalities" field if the given value is not nil.
func (_u *ModelConfigUpdate) SetNillableOutputModalities(v *string) *ModelConfigUpdate {
	if v != nil {
		_u.SetOutputModalities(*v)
	}
	return _u
}

// SetPricingMode sets the "pricing_mode" field.
func (_u *ModelConfigUpdate) SetPricingMode(v string) *ModelConfigUpdate {
	_u.mutation.SetPricingMode(v)
	return _u
}

// SetNillablePricingMode sets the "pricing_mode" field if the given value is not nil.
func (_u *ModelConfigUpdate) SetNillablePricingMode(v *string) *ModelConfigUpdate {
	if v != nil {
		_u.SetPricingMode(*v)
	}
	return _u
}

// SetInputPricePerMillion sets the "input_price_per_million" field.
func (_u *ModelConfigUpdate) SetInputPricePerMillion(v float64) *ModelConfigUpdate {
	_u.mutation.ResetInputPricePerMillion()
	_u.mutation.SetInputPricePerMillion(v)
	return _u
}

// SetNillableInputPricePerMillion sets the "input_price_per_million" field if the given value is not nil.
func (_u *ModelConfigUpdate) SetNillableInputPricePerMillion(v *float64) *ModelConfigUpdate {
	if v != nil {
		_u.SetInputPricePerMillion(*v)
	}
	return _u
}

// AddInputPricePerMillion adds value to the "input_price_per_million" field.
func (_u *ModelConfigUpdate) AddInputPricePerMillion(v float64) *ModelConfigUpdate {
	_u.mutation.AddInputPricePerMillion(v)
	return _u
}

// SetOutputPricePerMillion sets the "output_price_per_million" field.
func (_u *ModelConfigUpdate) SetOutputPricePerMillion(v float64) *ModelConfigUpdate {
	_u.mutation.ResetOutputPricePerMillion()
	_u.mutation.SetOutputPricePerMillion(v)
	return _u
}

// SetNillableOutputPricePerMillion sets the "output_price_per_million" field if the given value is not nil.
func (_u *ModelConfigUpdate) SetNillableOutputPricePerMillion(v *float64) *ModelConfigUpdate {
	if v != nil {
		_u.SetOutputPricePerMillion(*v)
	}
	return _u
}

// AddOutputPricePerMillion adds value to the "output_price_per_million" field.
func (_u *ModelConfigUpdate) AddOutputPricePerMillion(v float64) *ModelConfigUpdate {
	_u.mutation.AddOutputPricePerMillion(v)
	return _u
}

// SetCachedPricePerMillion sets the "cached_price_per_million" field.
func (_u *ModelConfigUpdate) SetCachedPricePerMillion(v float64) *ModelConfigUpdate {
	_u.mutation.ResetCachedPricePerMillion()
	_u.mutation.SetCachedPricePerMillion(v)
	return _u
}

// SetNillableCachedPricePerMillion sets the "cached_price_per_million" field if the given value is not nil.
func (_u *ModelConfigUpdate) SetNillableCachedPricePerMillion(v *float64) *ModelConfigUpdate {
	if v != nil {
		_u.SetCachedPricePerMillion(*v)
	}
	return _u
}

// AddCachedPricePerMillion adds value to the "cached_price_per_million" field.
func (_u *ModelConfigUpdate) AddCachedPricePerMillion(v float64) *ModelConfigUpdate {
	_u.mutation.AddCachedPricePerMillion(v)
	return _u
}

// SetCacheReadPricePerMillion sets the "cache_read_price_per_million" field.
func (_u *ModelConfigUpdate) SetCacheReadPricePerMillion(v float64) *ModelConfigUpdate {
	_u.mutation.ResetCacheReadPricePerMillion()
	_u.mutation.SetCacheReadPricePerMillion(v)
	return _u
}

// SetNillableCacheReadPricePerMillion sets the "cache_read_price_per_million" field if the given value is not nil.
func (_u *ModelConfigUpdate) SetNillableCacheReadPricePerMillion(v *float64) *ModelConfigUpdate {
	if v != nil {
		_u.SetCacheReadPricePerMillion(*v)
	}
	return _u
}

// AddCacheReadPricePerMillion adds value to the "cache_read_price_per_million" field.
func (_u *ModelConfigUpdate) AddCacheReadPricePerMillion(v float64) *ModelConfigUpdate {
	_u.mutation.AddCacheReadPricePerMillion(v)
	return _u
}

// SetCacheWritePricePerMillion sets the "cache_write_price_per_million" field.
func (_u *ModelConfigUpdate) SetCacheWritePricePerMillion(v float64) *ModelConfigUpdate {
	_u.mutation.ResetCacheWritePricePerMillion()
	_u.mutation.SetCacheWritePricePerMillion(v)
	return _u
}

// SetNillableCacheWritePricePerMillion sets the "cache_write_price_per_million" field if the given value is not nil.
func (_u *ModelConfigUpdate) SetNillableCacheWritePricePerMillion(v *float64) *ModelConfigUpdate {
	if v != nil {
		_u.SetCacheWritePricePerMillion(*v)
	}
	return _u
}

// AddCacheWritePricePerMillion adds value to the "cache_write_price_per_million" field.
func (_u *ModelConfigUpdate) AddCacheWritePricePerMillion(v float64) *ModelConfigUpdate {
	_u.mutation.AddCacheWritePricePerMillion(v)
	return _u
}

// SetPricePerCall sets the "price_per_call" field.
func (_u *ModelConfigUpdate) SetPricePerCall(v float64) *ModelConfigUpdate {
	_u.mutation.ResetPricePerCall()
	_u.mutation.SetPricePerCall(v)
	return _u
}

// SetNillablePricePerCall sets the "price_per_call" field if the given value is not nil.
func (_u *ModelConfigUpdate) SetNillablePricePerCall(v *float64) *ModelConfigUpdate {
	if v != nil {
		_u.SetPricePerCall(*v)
	}
	return _u
}

// AddPricePerCall adds value to the "price_per_call" field.
func (_u *ModelConfigUpdate) AddPricePerCall(v float64) *ModelConfigUpdate {
	_u.mutation.AddPricePerCall(v)
	return _u
}

// SetSource sets the "source" field.
func (_u *ModelConfigUpdate) SetSource(v string) *ModelConfigUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *ModelConfigUpdate) SetNillableSource(v *string) *ModelConfigUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelConfigUpdate) SetUpdatedAt(v time.Time) *ModelConfigUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ModelConfigUpdate) SetNillableUpdatedAt(v *time.Time) *ModelConfigUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the ModelConfigMutation object of the builder.
func (_u *ModelConfigUpdate) Mutation() *ModelConfigMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ModelConfigUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ModelConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ModelConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(modelconfig.Table, modelconfig.Columns, sqlgraph.NewFieldSpec(modelconfig.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(modelconfig.FieldTenantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(modelconfig.FieldModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.OwnedBy(); ok {
		_spec.SetField(modelconfig.FieldOwnedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(modelconfig.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(modelconfig.FieldEnabled, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEnabled(); ok {
		_spec.AddField(modelconfig.FieldEnabled, field.TypeInt, value)
	}
	if value, ok := _u.mutation.InputModalities(); ok {
		_spec.SetField(modelconfig.FieldInputModalities, field.TypeString, value)
	}
	if value, ok := _u.mutation.OutputModalities(); ok {
		_spec.SetField(modelconfig.FieldOutputModalities, field.TypeString, value)
	}
	if value, ok := _u.mutation.PricingMode(); ok {
		_spec.SetField(modelconfig.FieldPricingMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputPricePerMillion(); ok {
		_spec.SetField(modelconfig.FieldInputPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedInputPricePerMillion(); ok {
		_spec.AddField(modelconfig.FieldInputPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OutputPricePerMillion(); ok {
		_spec.SetField(modelconfig.FieldOutputPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOutputPricePerMillion(); ok {
		_spec.AddField(modelconfig.FieldOutputPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CachedPricePerMillion(); ok {
		_spec.SetField(modelconfig.FieldCachedPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCachedPricePerMillion(); ok {
		_spec.AddField(modelconfig.FieldCachedPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CacheReadPricePerMillion(); ok {
		_spec.SetField(modelconfig.FieldCacheReadPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadPricePerMillion(); ok {
		_spec.AddField(modelconfig.FieldCacheReadPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CacheWritePricePerMillion(); ok {
		_spec.SetField(modelconfig.FieldCacheWritePricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheWritePricePerMillion(); ok {
		_spec.AddField(modelconfig.FieldCacheWritePricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PricePerCall(); ok {
		_spec.SetField(modelconfig.FieldPricePerCall, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPricePerCall(); ok {
		_spec.AddField(modelconfig.FieldPricePerCall, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(modelconfig.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ModelConfigUpdateOne is the builder for updating a single ModelConfig entity.
type ModelConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ModelConfigMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *ModelConfigUpdateOne) SetTenantID(v string) *ModelConfigUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *ModelConfigUpdateOne) SetNillableTenantID(v *string) *ModelConfigUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *ModelConfigUpdateOne) SetModelID(v string) *ModelConfigUpdateOne {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *ModelConfigUpdateOne) SetNillableModelID(v *string) *ModelConfigUpdateOne {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// SetOwnedBy sets the "owned_by" field.
func (_u *ModelConfigUpdateOne) SetOwnedBy(v string) *ModelConfigUpdateOne {
	_u.mutation.SetOwnedBy(v)
	return _u
}

// SetNillableOwnedBy sets the "owned_by" field if the given value is not nil.
func (_u *ModelConfigUpdateOne) SetNillableOwnedBy(v *string) *ModelConfigUpdateOne {
	if v != nil {
		_u.SetOwnedBy(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ModelConfigUpdateOne) SetDescription(v string) *ModelConfigUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ModelConfigUpdateOne) SetNillableDescription(v *string) *ModelConfigUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ModelConfigUpdateOne) SetEnabled(v int) *ModelConfigUpdateOne {
	_u.mutation.ResetEnabled()
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ModelConfigUpdateOne) SetNillableEnabled(v *int) *ModelConfigUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// AddEnabled adds value to the "enabled" field.
func (_u *ModelConfigUpdateOne) AddEnabled(v int) *ModelConfigUpdateOne {
	_u.mutation.AddEnabled(v)
	return _u
}

// SetInputModalities sets the "input_modalities" field.
func (_u *ModelConfigUpdateOne) SetInputModalities(v string) *ModelConfigUpdateOne {
	_u.mutation.SetInputModalities(v)
	return _u
}

// SetNillableInputModalities sets the "input_modalities" field if the given value is not nil.
func (_u *ModelConfigUpdateOne) SetNillableInputModalities(v *string) *ModelConfigUpdateOne {
	if v != nil {
		_u.SetInputModalities(*v)
	}
	return _u
}

// SetOutputModalities sets the "output_modalities" field.
func (_u *ModelConfigUpdateOne) SetOutputModalities(v string) *ModelConfigUpdateOne {
	_u.mutation.SetOutputModalities(v)
	return _u
}

// SetNillableOutputModalities sets the "output_modalities" field if the given value is not nil.
func (_u *ModelConfigUpdateOne) SetNillableOutputModalities(v *string) *ModelConfigUpdateOne {
	if v != nil {
		_u.SetOutputModalities(*v)
	}
	return _u
}

// SetPricingMode sets the "pricing_mode" field.
func (_u *ModelConfigUpdateOne) SetPricingMode(v string) *ModelConfigUpdateOne {
	_u.mutation.SetPricingMode(v)
	return _u
}

// SetNillablePricingMode sets the "pricing_mode" field if the given value is not nil.
func (_u *ModelConfigUpdateOne) SetNillablePricingMode(v *string) *ModelConfigUpdateOne {
	if v != nil {
		_u.SetPricingMode(*v)
	}
	return _u
}

// SetInputPricePerMillion sets the "input_price_per_million" field.
func (_u *ModelConfigUpdateOne) SetInputPricePerMillion(v float64) *ModelConfigUpdateOne {
	_u.mutation.ResetInputPricePerMillion()
	_u.mutation.SetInputPricePerMillion(v)
	return _u
}

// SetNillableInputPricePerMillion sets the "input_price_per_million" field if the given value is not nil.
func (_u *ModelConfigUpdateOne) SetNillableInputPricePerMillion(v *float64) *ModelConfigUpdateOne {
	if v != nil {
		_u.SetInputPricePerMillion(*v)
	}
	return _u
}

// AddInputPricePerMillion adds value to the "input_price_per_million" field.
func (_u *ModelConfigUpdateOne) AddInputPricePerMillion(v float64) *ModelConfigUpdateOne {
	_u.mutation.AddInputPricePerMillion(v)
	return _u
}

// SetOutputPricePerMillion sets the "output_price_per_million" field.
func (_u *ModelConfigUpdateOne) SetOutputPricePerMillion(v float64) *ModelConfigUpdateOne {
	_u.mutation.ResetOutputPricePerMillion()
	_u.mutation.SetOutputPricePerMillion(v)
	return _u
}

// SetNillableOutputPricePerMillion sets the "output_price_per_million" field if the given value is not nil.
func (_u *ModelConfigUpdateOne) SetNillableOutputPricePerMillion(v *float64) *ModelConfigUpdateOne {
	if v != nil {
		_u.SetOutputPricePerMillion(*v)
	}
	return _u
}

// AddOutputPricePerMillion adds value to the "output_price_per_million" field.
func (_u *ModelConfigUpdateOne) AddOutputPricePerMillion(v float64) *ModelConfigUpdateOne {
	_u.mutation.AddOutputPricePerMillion(v)
	return _u
}

// SetCachedPricePerMillion sets the "cached_price_per_million" field.
func (_u *ModelConfigUpdateOne) SetCachedPricePerMillion(v float64) *ModelConfigUpdateOne {
	_u.mutation.ResetCachedPricePerMillion()
	_u.mutation.SetCachedPricePerMillion(v)
	return _u
}

// SetNillableCachedPricePerMillion sets the "cached_price_per_million" field if the given value is not nil.
func (_u *ModelConfigUpdateOne) SetNillableCachedPricePerMillion(v *float64) *ModelConfigUpdateOne {
	if v != nil {
		_u.SetCachedPricePerMillion(*v)
	}
	return _u
}

// AddCachedPricePerMillion adds value to the "cached_price_per_million" field.
func (_u *ModelConfigUpdateOne) AddCachedPricePerMillion(v float64) *ModelConfigUpdateOne {
	_u.mutation.AddCachedPricePerMillion(v)
	return _u
}

// SetCacheReadPricePerMillion sets the "cache_read_price_per_million" field.
func (_u *ModelConfigUpdateOne) SetCacheReadPricePerMillion(v float64) *ModelConfigUpdateOne {
	_u.mutation.ResetCacheReadPricePerMillion()
	_u.mutation.SetCacheReadPricePerMillion(v)
	return _u
}

// SetNillableCacheReadPricePerMillion sets the "cache_read_price_per_million" field if the given value is not nil.
func (_u *ModelConfigUpdateOne) SetNillableCacheReadPricePerMillion(v *float64) *ModelConfigUpdateOne {
	if v != nil {
		_u.SetCacheReadPricePerMillion(*v)
	}
	return _u
}

// AddCacheReadPricePerMillion adds value to the "cache_read_price_per_million" field.
func (_u *ModelConfigUpdateOne) AddCacheReadPricePerMillion(v float64) *ModelConfigUpdateOne {
	_u.mutation.AddCacheReadPricePerMillion(v)
	return _u
}

// SetCacheWritePricePerMillion sets the "cache_write_price_per_million" field.
func (_u *ModelConfigUpdateOne) SetCacheWritePricePerMillion(v float64) *ModelConfigUpdateOne {
	_u.mutation.ResetCacheWritePricePerMillion()
	_u.mutation.SetCacheWritePricePerMillion(v)
	return _u
}

// SetNillableCacheWritePricePerMillion sets the "cache_write_price_per_million" field if the given value is not nil.
func (_u *ModelConfigUpdateOne) SetNillableCacheWritePricePerMillion(v *float64) *ModelConfigUpdateOne {
	if v != nil {
		_u.SetCacheWritePricePerMillion(*v)
	}
	return _u
}

// AddCacheWritePricePerMillion adds value to the "cache_write_price_per_million" field.
func (_u *ModelConfigUpdateOne) AddCacheWritePricePerMillion(v float64) *ModelConfigUpdateOne {
	_u.mutation.AddCacheWritePricePerMillion(v)
	return _u
}

// SetPricePerCall sets the "price_per_call" field.
func (_u *ModelConfigUpdateOne) SetPricePerCall(v float64) *ModelConfigUpdateOne {
	_u.mutation.ResetPricePerCall()
	_u.mutation.SetPricePerCall(v)
	return _u
}

// SetNillablePricePerCall sets the "price_per_call" field if the given value is not nil.
func (_u *ModelConfigUpdateOne) SetNillablePricePerCall(v *float64) *ModelConfigUpdateOne {
	if v != nil {
		_u.SetPricePerCall(*v)
	}
	return _u
}

// AddPricePerCall adds value to the "price_per_call" field.
func (_u *ModelConfigUpdateOne) AddPricePerCall(v float64) *ModelConfigUpdateOne {
	_u.mutation.AddPricePerCall(v)
	return _u
}

// SetSource sets the "source" field.
func (_u *ModelConfigUpdateOne) SetSource(v string) *ModelConfigUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *ModelConfigUpdateOne) SetNillableSource(v *string) *ModelConfigUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelConfigUpdateOne) SetUpdatedAt(v time.Time) *ModelConfigUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ModelConfigUpdateOne) SetNillableUpdatedAt(v *time.Time) *ModelConfigUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the ModelConfigMutation object of the builder.
func (_u *ModelConfigUpdateOne) Mutation() *ModelConfigMutation {
	return _u.mutation
}

// Where appends a list predicates to the ModelConfigUpdate builder.
func (_u *ModelConfigUpdateOne) Where(ps ...predicate.ModelConfig) *ModelConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ModelConfigUpdateOne) Select(field string, fields ...string) *ModelConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ModelConfig entity.
func (_u *ModelConfigUpdateOne) Save(ctx context.Context) (*ModelConfig, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelConfigUpdateOne) SaveX(ctx context.Context) *ModelConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ModelConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ModelConfigUpdateOne) sqlSave(ctx context.Context) (_node *ModelConfig, err error) {
	_spec := sqlgraph.NewUpdateSpec(modelconfig.Table, modelconfig.Columns, sqlgraph.NewFieldSpec(modelconfig.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ModelConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, modelconfig.FieldID)
		for _, f := range fields {
			if !modelconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != modelconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(modelconfig.FieldTenantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(modelconfig.FieldModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.OwnedBy(); ok {
		_spec.SetField(modelconfig.FieldOwnedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(modelconfig.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(modelconfig.FieldEnabled, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEnabled(); ok {
		_spec.AddField(modelconfig.FieldEnabled, field.TypeInt, value)
	}
	if value, ok := _u.mutation.InputModalities(); ok {
		_spec.SetField(modelconfig.FieldInputModalities, field.TypeString, value)
	}
	if value, ok := _u.mutation.OutputModalities(); ok {
		_spec.SetField(modelconfig.FieldOutputModalities, field.TypeString, value)
	}
	if value, ok := _u.mutation.PricingMode(); ok {
		_spec.SetField(modelconfig.FieldPricingMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputPricePerMillion(); ok {
		_spec.SetField(modelconfig.FieldInputPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedInputPricePerMillion(); ok {
		_spec.AddField(modelconfig.FieldInputPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OutputPricePerMillion(); ok {
		_spec.SetField(modelconfig.FieldOutputPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOutputPricePerMillion(); ok {
		_spec.AddField(modelconfig.FieldOutputPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CachedPricePerMillion(); ok {
		_spec.SetField(modelconfig.FieldCachedPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCachedPricePerMillion(); ok {
		_spec.AddField(modelconfig.FieldCachedPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CacheReadPricePerMillion(); ok {
		_spec.SetField(modelconfig.FieldCacheReadPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadPricePerMillion(); ok {
		_spec.AddField(modelconfig.FieldCacheReadPricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CacheWritePricePerMillion(); ok {
		_spec.SetField(modelconfig.FieldCacheWritePricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheWritePricePerMillion(); ok {
		_spec.AddField(modelconfig.FieldCacheWritePricePerMillion, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PricePerCall(); ok {
		_spec.SetField(modelconfig.FieldPricePerCall, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPricePerCall(); ok {
		_spec.AddField(modelconfig.FieldPricePerCall, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(modelconfig.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ModelConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
