// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/router-for-me/CLIProxyAPI/v6/internal/storage/postgres/ent/predicate"
	"github.com/router-for-me/CLIProxyAPI/v6/internal/storage/postgres/ent/requestlog"
)

// RequestLogUpdate is the builder for updating RequestLog entities.
type RequestLogUpdate struct {
	config
	hooks    []Hook
	mutation *RequestLogMutation
}

// Where appends a list predicates to the RequestLogUpdate builder.
func (_u *RequestLogUpdate) Where(ps ...predicate.RequestLog) *RequestLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *RequestLogUpdate) SetTenantID(v string) *RequestLogUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableTenantID(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetTimestamp sets the "timestamp" field.
func (_u *RequestLogUpdate) SetTimestamp(v time.Time) *RequestLogUpdate {
	_u.mutation.SetTimestamp(v)
	return _u
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableTimestamp(v *time.Time) *RequestLogUpdate {
	if v != nil {
		_u.SetTimestamp(*v)
	}
	return _u
}

// SetAPIKey sets the "api_key" field.
func (_u *RequestLogUpdate) SetAPIKey(v string) *RequestLogUpdate {
	_u.mutation.SetAPIKey(v)
	return _u
}

// SetNillableAPIKey sets the "api_key" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableAPIKey(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetAPIKey(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *RequestLogUpdate) SetAPIKeyID(v string) *RequestLogUpdate {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableAPIKeyID(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// SetAuthSubjectID sets the "auth_subject_id" field.
func (_u *RequestLogUpdate) SetAuthSubjectID(v string) *RequestLogUpdate {
	_u.mutation.SetAuthSubjectID(v)
	return _u
}

// SetNillableAuthSubjectID sets the "auth_subject_id" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableAuthSubjectID(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetAuthSubjectID(*v)
	}
	return _u
}

// SetAPIKeyName sets the "api_key_name" field.
func (_u *RequestLogUpdate) SetAPIKeyName(v string) *RequestLogUpdate {
	_u.mutation.SetAPIKeyName(v)
	return _u
}

// SetNillableAPIKeyName sets the "api_key_name" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableAPIKeyName(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetAPIKeyName(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *RequestLogUpdate) SetModel(v string) *RequestLogUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableModel(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetUpstreamModel sets the "upstream_model" field.
func (_u *RequestLogUpdate) SetUpstreamModel(v string) *RequestLogUpdate {
	_u.mutation.SetUpstreamModel(v)
	return _u
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableUpstreamModel(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetUpstreamModel(*v)
	}
	return _u
}

// SetVisionFallbackModel sets the "vision_fallback_model" field.
func (_u *RequestLogUpdate) SetVisionFallbackModel(v string) *RequestLogUpdate {
	_u.mutation.SetVisionFallbackModel(v)
	return _u
}

// SetNillableVisionFallbackModel sets the "vision_fallback_model" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableVisionFallbackModel(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetVisionFallbackModel(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *RequestLogUpdate) SetSource(v string) *RequestLogUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableSource(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetChannelName sets the "channel_name" field.
func (_u *RequestLogUpdate) SetChannelName(v string) *RequestLogUpdate {
	_u.mutation.SetChannelName(v)
	return _u
}

// SetNillableChannelName sets the "channel_name" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableChannelName(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetChannelName(*v)
	}
	return _u
}

// SetAuthIndex sets the "auth_index" field.
func (_u *RequestLogUpdate) SetAuthIndex(v string) *RequestLogUpdate {
	_u.mutation.SetAuthIndex(v)
	return _u
}

// SetNillableAuthIndex sets the "auth_index" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableAuthIndex(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetAuthIndex(*v)
	}
	return _u
}

// SetFailed sets the "failed" field.
func (_u *RequestLogUpdate) SetFailed(v int) *RequestLogUpdate {
	_u.mutation.ResetFailed()
	_u.mutation.SetFailed(v)
	return _u
}

// SetNillableFailed sets the "failed" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableFailed(v *int) *RequestLogUpdate {
	if v != nil {
		_u.SetFailed(*v)
	}
	return _u
}

// AddFailed adds value to the "failed" field.
func (_u *RequestLogUpdate) AddFailed(v int) *RequestLogUpdate {
	_u.mutation.AddFailed(v)
	return _u
}

// SetStreaming sets the "streaming" field.
func (_u *RequestLogUpdate) SetStreaming(v int) *RequestLogUpdate {
	_u.mutation.ResetStreaming()
	_u.mutation.SetStreaming(v)
	return _u
}

// SetNillableStreaming sets the "streaming" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableStreaming(v *int) *RequestLogUpdate {
	if v != nil {
		_u.SetStreaming(*v)
	}
	return _u
}

// AddStreaming adds value to the "streaming" field.
func (_u *RequestLogUpdate) AddStreaming(v int) *RequestLogUpdate {
	_u.mutation.AddStreaming(v)
	return _u
}

// SetLatencyMs sets the "latency_ms" field.
func (_u *RequestLogUpdate) SetLatencyMs(v int64) *RequestLogUpdate {
	_u.mutation.ResetLatencyMs()
	_u.mutation.SetLatencyMs(v)
	return _u
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableLatencyMs(v *int64) *RequestLogUpdate {
	if v != nil {
		_u.SetLatencyMs(*v)
	}
	return _u
}

// AddLatencyMs adds value to the "latency_ms" field.
func (_u *RequestLogUpdate) AddLatencyMs(v int64) *RequestLogUpdate {
	_u.mutation.AddLatencyMs(v)
	return _u
}

// SetFirstTokenMs sets the "first_token_ms" field.
func (_u *RequestLogUpdate) SetFirstTokenMs(v int64) *RequestLogUpdate {
	_u.mutation.ResetFirstTokenMs()
	_u.mutation.SetFirstTokenMs(v)
	return _u
}

// SetNillableFirstTokenMs sets the "first_token_ms" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableFirstTokenMs(v *int64) *RequestLogUpdate {
	if v != nil {
		_u.SetFirstTokenMs(*v)
	}
	return _u
}

// AddFirstTokenMs adds value to the "first_token_ms" field.
func (_u *RequestLogUpdate) AddFirstTokenMs(v int64) *RequestLogUpdate {
	_u.mutation.AddFirstTokenMs(v)
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *RequestLogUpdate) SetInputTokens(v int64) *RequestLogUpdate {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableInputTokens(v *int64) *RequestLogUpdate {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *RequestLogUpdate) AddInputTokens(v int64) *RequestLogUpdate {
	_u.mutation.AddInputTokens(v)
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *RequestLogUpdate) SetOutputTokens(v int64) *RequestLogUpdate {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableOutputTokens(v *int64) *RequestLogUpdate {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *RequestLogUpdate) AddOutputTokens(v int64) *RequestLogUpdate {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// SetReasoningTokens sets the "reasoning_tokens" field.
func (_u *RequestLogUpdate) SetReasoningTokens(v int64) *RequestLogUpdate {
	_u.mutation.ResetReasoningTokens()
	_u.mutation.SetReasoningTokens(v)
	return _u
}

// SetNillableReasoningTokens sets the "reasoning_tokens" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableReasoningTokens(v *int64) *RequestLogUpdate {
	if v != nil {
		_u.SetReasoningTokens(*v)
	}
	return _u
}

// AddReasoningTokens adds value to the "reasoning_tokens" field.
func (_u *RequestLogUpdate) AddReasoningTokens(v int64) *RequestLogUpdate {
	_u.mutation.AddReasoningTokens(v)
	return _u
}

// SetCachedTokens sets the "cached_tokens" field.
func (_u *RequestLogUpdate) SetCachedTokens(v int64) *RequestLogUpdate {
	_u.mutation.ResetCachedTokens()
	_u.mutation.SetCachedTokens(v)
	return _u
}

// SetNillableCachedTokens sets the "cached_tokens" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableCachedTokens(v *int64) *RequestLogUpdate {
	if v != nil {
		_u.SetCachedTokens(*v)
	}
	return _u
}

// AddCachedTokens adds value to the "cached_tokens" field.
func (_u *RequestLogUpdate) AddCachedTokens(v int64) *RequestLogUpdate {
	_u.mutation.AddCachedTokens(v)
	return _u
}

// SetTotalTokens sets the "total_tokens" field.
func (_u *RequestLogUpdate) SetTotalTokens(v int64) *RequestLogUpdate {
	_u.mutation.ResetTotalTokens()
	_u.mutation.SetTotalTokens(v)
	return _u
}

// SetNillableTotalTokens sets the "total_tokens" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableTotalTokens(v *int64) *RequestLogUpdate {
	if v != nil {
		_u.SetTotalTokens(*v)
	}
	return _u
}

// AddTotalTokens adds value to the "total_tokens" field.
func (_u *RequestLogUpdate) AddTotalTokens(v int64) *RequestLogUpdate {
	_u.mutation.AddTotalTokens(v)
	return _u
}

// SetCost sets the "cost" field.
func (_u *RequestLogUpdate) SetCost(v float64) *RequestLogUpdate {
	_u.mutation.ResetCost()
	_u.mutation.SetCost(v)
	return _u
}

// SetNillableCost sets the "cost" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableCost(v *float64) *RequestLogUpdate {
	if v != nil {
		_u.SetCost(*v)
	}
	return _u
}

// AddCost adds value to the "cost" field.
func (_u *RequestLogUpdate) AddCost(v float64) *RequestLogUpdate {
	_u.mutation.AddCost(v)
	return _u
}

// SetInputContent sets the "input_content" field.
func (_u *RequestLogUpdate) SetInputContent(v string) *RequestLogUpdate {
	_u.mutation.SetInputContent(v)
	return _u
}

// SetNillableInputContent sets the "input_content" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableInputContent(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetInputContent(*v)
	}
	return _u
}

// SetOutputContent sets the "output_content" field.
func (_u *RequestLogUpdate) SetOutputContent(v string) *RequestLogUpdate {
	_u.mutation.SetOutputContent(v)
	return _u
}

// SetNillableOutputContent sets the "output_content" field if the given value is not nil.
func (_u *RequestLogUpdate) SetNillableOutputContent(v *string) *RequestLogUpdate {
	if v != nil {
		_u.SetOutputContent(*v)
	}
	return _u
}

// Mutation returns the RequestLogMutation object of the builder.
func (_u *RequestLogUpdate) Mutation() *RequestLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RequestLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequestLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RequestLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequestLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RequestLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(requestlog.Table, requestlog.Columns, sqlgraph.NewFieldSpec(requestlog.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(requestlog.FieldTenantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Timestamp(); ok {
		_spec.SetField(requestlog.FieldTimestamp, field.TypeTime, value)
	}
	if value, ok := _u.mutation.APIKey(); ok {
		_spec.SetField(requestlog.FieldAPIKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(requestlog.FieldAPIKeyID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthSubjectID(); ok {
		_spec.SetField(requestlog.FieldAuthSubjectID, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKeyName(); ok {
		_spec.SetField(requestlog.FieldAPIKeyName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(requestlog.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamModel(); ok {
		_spec.SetField(requestlog.FieldUpstreamModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.VisionFallbackModel(); ok {
		_spec.SetField(requestlog.FieldVisionFallbackModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(requestlog.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChannelName(); ok {
		_spec.SetField(requestlog.FieldChannelName, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthIndex(); ok {
		_spec.SetField(requestlog.FieldAuthIndex, field.TypeString, value)
	}
	if value, ok := _u.mutation.Failed(); ok {
		_spec.SetField(requestlog.FieldFailed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFailed(); ok {
		_spec.AddField(requestlog.FieldFailed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Streaming(); ok {
		_spec.SetField(requestlog.FieldStreaming, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStreaming(); ok {
		_spec.AddField(requestlog.FieldStreaming, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LatencyMs(); ok {
		_spec.SetField(requestlog.FieldLatencyMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLatencyMs(); ok {
		_spec.AddField(requestlog.FieldLatencyMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FirstTokenMs(); ok {
		_spec.SetField(requestlog.FieldFirstTokenMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFirstTokenMs(); ok {
		_spec.AddField(requestlog.FieldFirstTokenMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(requestlog.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(requestlog.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(requestlog.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(requestlog.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ReasoningTokens(); ok {
		_spec.SetField(requestlog.FieldReasoningTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReasoningTokens(); ok {
		_spec.AddField(requestlog.FieldReasoningTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CachedTokens(); ok {
		_spec.SetField(requestlog.FieldCachedTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCachedTokens(); ok {
		_spec.AddField(requestlog.FieldCachedTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalTokens(); ok {
		_spec.SetField(requestlog.FieldTotalTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalTokens(); ok {
		_spec.AddField(requestlog.FieldTotalTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Cost(); ok {
		_spec.SetField(requestlog.FieldCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCost(); ok {
		_spec.AddField(requestlog.FieldCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.InputContent(); ok {
		_spec.SetField(requestlog.FieldInputContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.OutputContent(); ok {
		_spec.SetField(requestlog.FieldOutputContent, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requestlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RequestLogUpdateOne is the builder for updating a single RequestLog entity.
type RequestLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RequestLogMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *RequestLogUpdateOne) SetTenantID(v string) *RequestLogUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableTenantID(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetTimestamp sets the "timestamp" field.
func (_u *RequestLogUpdateOne) SetTimestamp(v time.Time) *RequestLogUpdateOne {
	_u.mutation.SetTimestamp(v)
	return _u
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableTimestamp(v *time.Time) *RequestLogUpdateOne {
	if v != nil {
		_u.SetTimestamp(*v)
	}
	return _u
}

// SetAPIKey sets the "api_key" field.
func (_u *RequestLogUpdateOne) SetAPIKey(v string) *RequestLogUpdateOne {
	_u.mutation.SetAPIKey(v)
	return _u
}

// SetNillableAPIKey sets the "api_key" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableAPIKey(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetAPIKey(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *RequestLogUpdateOne) SetAPIKeyID(v string) *RequestLogUpdateOne {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableAPIKeyID(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// SetAuthSubjectID sets the "auth_subject_id" field.
func (_u *RequestLogUpdateOne) SetAuthSubjectID(v string) *RequestLogUpdateOne {
	_u.mutation.SetAuthSubjectID(v)
	return _u
}

// SetNillableAuthSubjectID sets the "auth_subject_id" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableAuthSubjectID(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetAuthSubjectID(*v)
	}
	return _u
}

// SetAPIKeyName sets the "api_key_name" field.
func (_u *RequestLogUpdateOne) SetAPIKeyName(v string) *RequestLogUpdateOne {
	_u.mutation.SetAPIKeyName(v)
	return _u
}

// SetNillableAPIKeyName sets the "api_key_name" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableAPIKeyName(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetAPIKeyName(*v)
	}
	return _u
}

// SetModel sets the "model" field.
func (_u *RequestLogUpdateOne) SetModel(v string) *RequestLogUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableModel(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetUpstreamModel sets the "upstream_model" field.
func (_u *RequestLogUpdateOne) SetUpstreamModel(v string) *RequestLogUpdateOne {
	_u.mutation.SetUpstreamModel(v)
	return _u
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableUpstreamModel(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetUpstreamModel(*v)
	}
	return _u
}

// SetVisionFallbackModel sets the "vision_fallback_model" field.
func (_u *RequestLogUpdateOne) SetVisionFallbackModel(v string) *RequestLogUpdateOne {
	_u.mutation.SetVisionFallbackModel(v)
	return _u
}

// SetNillableVisionFallbackModel sets the "vision_fallback_model" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableVisionFallbackModel(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetVisionFallbackModel(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *RequestLogUpdateOne) SetSource(v string) *RequestLogUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableSource(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetChannelName sets the "channel_name" field.
func (_u *RequestLogUpdateOne) SetChannelName(v string) *RequestLogUpdateOne {
	_u.mutation.SetChannelName(v)
	return _u
}

// SetNillableChannelName sets the "channel_name" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableChannelName(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetChannelName(*v)
	}
	return _u
}

// SetAuthIndex sets the "auth_index" field.
func (_u *RequestLogUpdateOne) SetAuthIndex(v string) *RequestLogUpdateOne {
	_u.mutation.SetAuthIndex(v)
	return _u
}

// SetNillableAuthIndex sets the "auth_index" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableAuthIndex(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetAuthIndex(*v)
	}
	return _u
}

// SetFailed sets the "failed" field.
func (_u *RequestLogUpdateOne) SetFailed(v int) *RequestLogUpdateOne {
	_u.mutation.ResetFailed()
	_u.mutation.SetFailed(v)
	return _u
}

// SetNillableFailed sets the "failed" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableFailed(v *int) *RequestLogUpdateOne {
	if v != nil {
		_u.SetFailed(*v)
	}
	return _u
}

// AddFailed adds value to the "failed" field.
func (_u *RequestLogUpdateOne) AddFailed(v int) *RequestLogUpdateOne {
	_u.mutation.AddFailed(v)
	return _u
}

// SetStreaming sets the "streaming" field.
func (_u *RequestLogUpdateOne) SetStreaming(v int) *RequestLogUpdateOne {
	_u.mutation.ResetStreaming()
	_u.mutation.SetStreaming(v)
	return _u
}

// SetNillableStreaming sets the "streaming" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableStreaming(v *int) *RequestLogUpdateOne {
	if v != nil {
		_u.SetStreaming(*v)
	}
	return _u
}

// AddStreaming adds value to the "streaming" field.
func (_u *RequestLogUpdateOne) AddStreaming(v int) *RequestLogUpdateOne {
	_u.mutation.AddStreaming(v)
	return _u
}

// SetLatencyMs sets the "latency_ms" field.
func (_u *RequestLogUpdateOne) SetLatencyMs(v int64) *RequestLogUpdateOne {
	_u.mutation.ResetLatencyMs()
	_u.mutation.SetLatencyMs(v)
	return _u
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableLatencyMs(v *int64) *RequestLogUpdateOne {
	if v != nil {
		_u.SetLatencyMs(*v)
	}
	return _u
}

// AddLatencyMs adds value to the "latency_ms" field.
func (_u *RequestLogUpdateOne) AddLatencyMs(v int64) *RequestLogUpdateOne {
	_u.mutation.AddLatencyMs(v)
	return _u
}

// SetFirstTokenMs sets the "first_token_ms" field.
func (_u *RequestLogUpdateOne) SetFirstTokenMs(v int64) *RequestLogUpdateOne {
	_u.mutation.ResetFirstTokenMs()
	_u.mutation.SetFirstTokenMs(v)
	return _u
}

// SetNillableFirstTokenMs sets the "first_token_ms" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableFirstTokenMs(v *int64) *RequestLogUpdateOne {
	if v != nil {
		_u.SetFirstTokenMs(*v)
	}
	return _u
}

// AddFirstTokenMs adds value to the "first_token_ms" field.
func (_u *RequestLogUpdateOne) AddFirstTokenMs(v int64) *RequestLogUpdateOne {
	_u.mutation.AddFirstTokenMs(v)
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *RequestLogUpdateOne) SetInputTokens(v int64) *RequestLogUpdateOne {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableInputTokens(v *int64) *RequestLogUpdateOne {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *RequestLogUpdateOne) AddInputTokens(v int64) *RequestLogUpdateOne {
	_u.mutation.AddInputTokens(v)
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *RequestLogUpdateOne) SetOutputTokens(v int64) *RequestLogUpdateOne {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableOutputTokens(v *int64) *RequestLogUpdateOne {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *RequestLogUpdateOne) AddOutputTokens(v int64) *RequestLogUpdateOne {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// SetReasoningTokens sets the "reasoning_tokens" field.
func (_u *RequestLogUpdateOne) SetReasoningTokens(v int64) *RequestLogUpdateOne {
	_u.mutation.ResetReasoningTokens()
	_u.mutation.SetReasoningTokens(v)
	return _u
}

// SetNillableReasoningTokens sets the "reasoning_tokens" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableReasoningTokens(v *int64) *RequestLogUpdateOne {
	if v != nil {
		_u.SetReasoningTokens(*v)
	}
	return _u
}

// AddReasoningTokens adds value to the "reasoning_tokens" field.
func (_u *RequestLogUpdateOne) AddReasoningTokens(v int64) *RequestLogUpdateOne {
	_u.mutation.AddReasoningTokens(v)
	return _u
}

// SetCachedTokens sets the "cached_tokens" field.
func (_u *RequestLogUpdateOne) SetCachedTokens(v int64) *RequestLogUpdateOne {
	_u.mutation.ResetCachedTokens()
	_u.mutation.SetCachedTokens(v)
	return _u
}

// SetNillableCachedTokens sets the "cached_tokens" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableCachedTokens(v *int64) *RequestLogUpdateOne {
	if v != nil {
		_u.SetCachedTokens(*v)
	}
	return _u
}

// AddCachedTokens adds value to the "cached_tokens" field.
func (_u *RequestLogUpdateOne) AddCachedTokens(v int64) *RequestLogUpdateOne {
	_u.mutation.AddCachedTokens(v)
	return _u
}

// SetTotalTokens sets the "total_tokens" field.
func (_u *RequestLogUpdateOne) SetTotalTokens(v int64) *RequestLogUpdateOne {
	_u.mutation.ResetTotalTokens()
	_u.mutation.SetTotalTokens(v)
	return _u
}

// SetNillableTotalTokens sets the "total_tokens" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableTotalTokens(v *int64) *RequestLogUpdateOne {
	if v != nil {
		_u.SetTotalTokens(*v)
	}
	return _u
}

// AddTotalTokens adds value to the "total_tokens" field.
func (_u *RequestLogUpdateOne) AddTotalTokens(v int64) *RequestLogUpdateOne {
	_u.mutation.AddTotalTokens(v)
	return _u
}

// SetCost sets the "cost" field.
func (_u *RequestLogUpdateOne) SetCost(v float64) *RequestLogUpdateOne {
	_u.mutation.ResetCost()
	_u.mutation.SetCost(v)
	return _u
}

// SetNillableCost sets the "cost" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableCost(v *float64) *RequestLogUpdateOne {
	if v != nil {
		_u.SetCost(*v)
	}
	return _u
}

// AddCost adds value to the "cost" field.
func (_u *RequestLogUpdateOne) AddCost(v float64) *RequestLogUpdateOne {
	_u.mutation.AddCost(v)
	return _u
}

// SetInputContent sets the "input_content" field.
func (_u *RequestLogUpdateOne) SetInputContent(v string) *RequestLogUpdateOne {
	_u.mutation.SetInputContent(v)
	return _u
}

// SetNillableInputContent sets the "input_content" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableInputContent(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetInputContent(*v)
	}
	return _u
}

// SetOutputContent sets the "output_content" field.
func (_u *RequestLogUpdateOne) SetOutputContent(v string) *RequestLogUpdateOne {
	_u.mutation.SetOutputContent(v)
	return _u
}

// SetNillableOutputContent sets the "output_content" field if the given value is not nil.
func (_u *RequestLogUpdateOne) SetNillableOutputContent(v *string) *RequestLogUpdateOne {
	if v != nil {
		_u.SetOutputContent(*v)
	}
	return _u
}

// Mutation returns the RequestLogMutation object of the builder.
func (_u *RequestLogUpdateOne) Mutation() *RequestLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the RequestLogUpdate builder.
func (_u *RequestLogUpdateOne) Where(ps ...predicate.RequestLog) *RequestLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RequestLogUpdateOne) Select(field string, fields ...string) *RequestLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RequestLog entity.
func (_u *RequestLogUpdateOne) Save(ctx context.Context) (*RequestLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequestLogUpdateOne) SaveX(ctx context.Context) *RequestLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RequestLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequestLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RequestLogUpdateOne) sqlSave(ctx context.Context) (_node *RequestLog, err error) {
	_spec := sqlgraph.NewUpdateSpec(requestlog.Table, requestlog.Columns, sqlgraph.NewFieldSpec(requestlog.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RequestLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, requestlog.FieldID)
		for _, f := range fields {
			if !requestlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != requestlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(requestlog.FieldTenantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Timestamp(); ok {
		_spec.SetField(requestlog.FieldTimestamp, field.TypeTime, value)
	}
	if value, ok := _u.mutation.APIKey(); ok {
		_spec.SetField(requestlog.FieldAPIKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(requestlog.FieldAPIKeyID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthSubjectID(); ok {
		_spec.SetField(requestlog.FieldAuthSubjectID, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKeyName(); ok {
		_spec.SetField(requestlog.FieldAPIKeyName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(requestlog.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamModel(); ok {
		_spec.SetField(requestlog.FieldUpstreamModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.VisionFallbackModel(); ok {
		_spec.SetField(requestlog.FieldVisionFallbackModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(requestlog.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChannelName(); ok {
		_spec.SetField(requestlog.FieldChannelName, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthIndex(); ok {
		_spec.SetField(requestlog.FieldAuthIndex, field.TypeString, value)
	}
	if value, ok := _u.mutation.Failed(); ok {
		_spec.SetField(requestlog.FieldFailed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFailed(); ok {
		_spec.AddField(requestlog.FieldFailed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Streaming(); ok {
		_spec.SetField(requestlog.FieldStreaming, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStreaming(); ok {
		_spec.AddField(requestlog.FieldStreaming, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LatencyMs(); ok {
		_spec.SetField(requestlog.FieldLatencyMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLatencyMs(); ok {
		_spec.AddField(requestlog.FieldLatencyMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FirstTokenMs(); ok {
		_spec.SetField(requestlog.FieldFirstTokenMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFirstTokenMs(); ok {
		_spec.AddField(requestlog.FieldFirstTokenMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(requestlog.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(requestlog.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(requestlog.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(requestlog.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ReasoningTokens(); ok {
		_spec.SetField(requestlog.FieldReasoningTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReasoningTokens(); ok {
		_spec.AddField(requestlog.FieldReasoningTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CachedTokens(); ok {
		_spec.SetField(requestlog.FieldCachedTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCachedTokens(); ok {
		_spec.AddField(requestlog.FieldCachedTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalTokens(); ok {
		_spec.SetField(requestlog.FieldTotalTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalTokens(); ok {
		_spec.AddField(requestlog.FieldTotalTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Cost(); ok {
		_spec.SetField(requestlog.FieldCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCost(); ok {
		_spec.AddField(requestlog.FieldCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.InputContent(); ok {
		_spec.SetField(requestlog.FieldInputContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.OutputContent(); ok {
		_spec.SetField(requestlog.FieldOutputContent, field.TypeString, value)
	}
	_node = &RequestLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requestlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
