// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/router-for-me/CLIProxyAPI/v6/internal/storage/postgres/ent/routingconfig"
)

// RoutingConfigCreate is the builder for creating a RoutingConfig entity.
type RoutingConfigCreate struct {
	config
	mutation *RoutingConfigMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *RoutingConfigCreate) SetTenantID(v string) *RoutingConfigCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *RoutingConfigCreate) SetNillableTenantID(v *string) *RoutingConfigCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetPayload sets the "payload" field.
func (_c *RoutingConfigCreate) SetPayload(v string) *RoutingConfigCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_c *RoutingConfigCreate) SetNillablePayload(v *string) *RoutingConfigCreate {
	if v != nil {
		_c.SetPayload(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RoutingConfigCreate) SetUpdatedAt(v string) *RoutingConfigCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RoutingConfigCreate) SetNillableUpdatedAt(v *string) *RoutingConfigCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RoutingConfigCreate) SetID(v int) *RoutingConfigCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *RoutingConfigCreate) SetNillableID(v *int) *RoutingConfigCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the RoutingConfigMutation object of the builder.
func (_c *RoutingConfigCreate) Mutation() *RoutingConfigMutation {
	return _c.mutation
}

// Save creates the RoutingConfig in the database.
func (_c *RoutingConfigCreate) Save(ctx context.Context) (*RoutingConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RoutingConfigCreate) SaveX(ctx context.Context) *RoutingConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RoutingConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RoutingConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RoutingConfigCreate) defaults() {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := routingconfig.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.Payload(); !ok {
		v := routingconfig.DefaultPayload
		_c.mutation.SetPayload(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := routingconfig.DefaultUpdatedAt
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := routingconfig.DefaultID
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RoutingConfigCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "RoutingConfig.tenant_id"`)}
	}
	if _, ok := _c.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "RoutingConfig.payload"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RoutingConfig.updated_at"`)}
	}
	return nil
}

func (_c *RoutingConfigCreate) sqlSave(ctx context.Context) (*RoutingConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RoutingConfigCreate) createSpec() (*RoutingConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &RoutingConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(routingconfig.Table, sqlgraph.NewFieldSpec(routingconfig.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(routingconfig.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(routingconfig.FieldPayload, field.TypeString, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(routingconfig.FieldUpdatedAt, field.TypeString, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// RoutingConfigCreateBulk is the builder for creating many RoutingConfig entities in bulk.
type RoutingConfigCreateBulk struct {
	config
	err      error
	builders []*RoutingConfigCreate
}

// Save creates the RoutingConfig entities in the database.
func (_c *RoutingConfigCreateBulk) Save(ctx context.Context) ([]*RoutingConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RoutingConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RoutingConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RoutingConfigCreateBulk) SaveX(ctx context.Context) []*RoutingConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RoutingConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RoutingConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
