// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/router-for-me/CLIProxyAPI/v6/internal/storage/postgres/ent/predicate"
	"github.com/router-for-me/CLIProxyAPI/v6/internal/storage/postgres/ent/routingconfig"
)

// RoutingConfigUpdate is the builder for updating RoutingConfig entities.
type RoutingConfigUpdate struct {
	config
	hooks    []Hook
	mutation *RoutingConfigMutation
}

// Where appends a list predicates to the RoutingConfigUpdate builder.
func (_u *RoutingConfigUpdate) Where(ps ...predicate.RoutingConfig) *RoutingConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *RoutingConfigUpdate) SetTenantID(v string) *RoutingConfigUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *RoutingConfigUpdate) SetNillableTenantID(v *string) *RoutingConfigUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *RoutingConfigUpdate) SetPayload(v string) *RoutingConfigUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_u *RoutingConfigUpdate) SetNillablePayload(v *string) *RoutingConfigUpdate {
	if v != nil {
		_u.SetPayload(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RoutingConfigUpdate) SetUpdatedAt(v string) *RoutingConfigUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *RoutingConfigUpdate) SetNillableUpdatedAt(v *string) *RoutingConfigUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the RoutingConfigMutation object of the builder.
func (_u *RoutingConfigUpdate) Mutation() *RoutingConfigMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RoutingConfigUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RoutingConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RoutingConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RoutingConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RoutingConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(routingconfig.Table, routingconfig.Columns, sqlgraph.NewFieldSpec(routingconfig.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(routingconfig.FieldTenantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(routingconfig.FieldPayload, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(routingconfig.FieldUpdatedAt, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{routingconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RoutingConfigUpdateOne is the builder for updating a single RoutingConfig entity.
type RoutingConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RoutingConfigMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *RoutingConfigUpdateOne) SetTenantID(v string) *RoutingConfigUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *RoutingConfigUpdateOne) SetNillableTenantID(v *string) *RoutingConfigUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *RoutingConfigUpdateOne) SetPayload(v string) *RoutingConfigUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_u *RoutingConfigUpdateOne) SetNillablePayload(v *string) *RoutingConfigUpdateOne {
	if v != nil {
		_u.SetPayload(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RoutingConfigUpdateOne) SetUpdatedAt(v string) *RoutingConfigUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *RoutingConfigUpdateOne) SetNillableUpdatedAt(v *string) *RoutingConfigUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// Mutation returns the RoutingConfigMutation object of the builder.
func (_u *RoutingConfigUpdateOne) Mutation() *RoutingConfigMutation {
	return _u.mutation
}

// Where appends a list predicates to the RoutingConfigUpdate builder.
func (_u *RoutingConfigUpdateOne) Where(ps ...predicate.RoutingConfig) *RoutingConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RoutingConfigUpdateOne) Select(field string, fields ...string) *RoutingConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RoutingConfig entity.
func (_u *RoutingConfigUpdateOne) Save(ctx context.Context) (*RoutingConfig, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RoutingConfigUpdateOne) SaveX(ctx context.Context) *RoutingConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RoutingConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RoutingConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RoutingConfigUpdateOne) sqlSave(ctx context.Context) (_node *RoutingConfig, err error) {
	_spec := sqlgraph.NewUpdateSpec(routingconfig.Table, routingconfig.Columns, sqlgraph.NewFieldSpec(routingconfig.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RoutingConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, routingconfig.FieldID)
		for _, f := range fields {
			if !routingconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != routingconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(routingconfig.FieldTenantID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(routingconfig.FieldPayload, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(routingconfig.FieldUpdatedAt, field.TypeString, value)
	}
	_node = &RoutingConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{routingconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
